import { deleteCatalogEntitySafely, deleteRow, getAdminProducts, getBrands, getCatalogEntityDependencies, getCategories, getPaymentMethods, getSettings, getTeams, removeCatalogEntityAsset, removePaymentMethodAsset, replaceProductRelations, saveProductImages, saveRow, saveSettings, supabase, uploadImage } from '../lib/api.js';
import { confirmAction, openModal } from '../components/modal.js';
import { toast } from '../components/toast.js';
import { $, $$, categoryInitials, currentPrice, escapeHtml, formatMoney, isPromoActive, localAsset, normalizeText, paymentInitials, setButtonLoading, slugify } from '../lib/helpers.js';

let products=[];let categories=[];let teams=[];let brands=[];
let activeSection='dashboard';
const PAGE_SIZE=20;
const STOCK_PAGE_SIZE=30;
const ENTITY_PAGE_SIZE=30;
const cleanText=normalizeText;
const debounce=(callback,delay=200)=>{let timer;return(...args)=>{clearTimeout(timer);timer=setTimeout(()=>callback(...args),delay);};};
const productImage=product=>product.product_images?.find(image=>image.is_primary)?.url||product.product_images?.[0]?.url||'../assets/images/product-white.svg';
const totalStock=product=>product.product_variants.reduce((sum,variant)=>sum+Number(variant.stock||0),0);
const isProductSoldOut=product=>product.force_sold_out||totalStock(product)===0;
const isProductLow=product=>product.force_last_units||(!product.force_sold_out&&product.product_variants.some(variant=>variant.stock>0&&variant.stock<=3));
const stockStatus=(stock,product=null)=>product?.force_sold_out||stock===0?{label:'Agotado',className:'sold'}:product?.force_last_units||stock<=3?{label:'Últimas unidades',className:'low'}:{label:'Disponible',className:'available'};

export async function initAdmin(){
  const{data:{session}}=await supabase.auth.getSession();
  if(!session){location.replace('login.html');return;}
  const{data:admin}=await supabase.from('admins').select('user_id').eq('user_id',session.user.id).maybeSingle();
  if(!admin){await supabase.auth.signOut();location.replace('login.html');return;}
  $('#logout-button').addEventListener('click',async()=>{await supabase.auth.signOut();location.replace('login.html');});
  setupDrawer();setupActionMenus();
  $('#admin-nav').addEventListener('click',event=>{const button=event.target.closest('[data-section]');if(!button)return;closeDrawer();navigateTo(button.dataset.section);});
  window.addEventListener('popstate',()=>loadSection(new URLSearchParams(location.search).get('section')||'dashboard'));
  await refreshData();await loadSection(new URLSearchParams(location.search).get('section')||'dashboard');
}

function setupActionMenus(){
  document.addEventListener('click',event=>{$$('.action-menu[open]').forEach(menu=>{if(!menu.contains(event.target))menu.open=false;});});
  document.addEventListener('keydown',event=>{if(event.key!=='Escape')return;const menu=document.querySelector('.action-menu[open]');if(!menu)return;event.preventDefault();menu.open=false;menu.querySelector('summary')?.focus();});
}

function setupDrawer(){
  const sidebar=$('#admin-sidebar');const backdrop=$('#admin-sidebar-backdrop');const menu=$('#admin-menu');const close=$('#admin-menu-close');
  menu.addEventListener('click',()=>{sidebar.classList.add('open');backdrop.hidden=false;requestAnimationFrame(()=>backdrop.classList.add('visible'));document.body.classList.add('no-scroll');menu.setAttribute('aria-expanded','true');close.focus();});
  close.addEventListener('click',closeDrawer);backdrop.addEventListener('click',closeDrawer);
  matchMedia('(min-width: 900px)').addEventListener('change',event=>{if(event.matches)closeDrawer();});
  document.addEventListener('keydown',event=>{if(!sidebar.classList.contains('open'))return;if(event.key==='Escape'){event.preventDefault();closeDrawer();return;}if(event.key!=='Tab')return;const focusable=[...sidebar.querySelectorAll('a[href],button:not([disabled])')];const first=focusable[0];const last=focusable.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}});
}

function closeDrawer(){
  const sidebar=$('#admin-sidebar');const backdrop=$('#admin-sidebar-backdrop');const menu=$('#admin-menu');if(!sidebar?.classList.contains('open'))return;
  sidebar.classList.remove('open');backdrop.classList.remove('visible');document.body.classList.remove('no-scroll');menu.setAttribute('aria-expanded','false');setTimeout(()=>{if(!sidebar.classList.contains('open'))backdrop.hidden=true;},210);menu.focus({preventScroll:true});
}

function navigateTo(section,params={}){
  const query=new URLSearchParams({section,...Object.fromEntries(Object.entries(params).filter(([,value])=>value!==''&&value!=null))});
  history.pushState({},'',`${location.pathname}?${query}`);loadSection(section);window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});
}

async function refreshData(){[products,categories,teams,brands]=await Promise.all([getAdminProducts(),getCategories({all:true}),getTeams({all:true}),getBrands({all:true})]);}

async function loadSection(section){
  if(!['dashboard','products','stock','categories','teams','brands','promotions','settings'].includes(section))section='dashboard';
  activeSection=section;$$('#admin-nav button').forEach(button=>button.classList.toggle('active',button.dataset.section===section));
  const root=$('#admin-content');root.innerHTML=['categories','teams','brands'].includes(section)?entityLoadingMarkup():'<div class="admin-loading"><span class="spinner"></span> Cargando…</div>';
  const loaders={dashboard:renderDashboard,products:renderProducts,stock:renderStock,categories:()=>renderEntities('categories'),teams:()=>renderEntities('teams'),brands:()=>renderEntities('brands'),promotions:renderPromotions,settings:renderSettings};
  try{await loaders[section]?.();}catch(error){console.error(error);root.innerHTML='<div class="empty-state"><h1>No pudimos cargar esta sección</h1><p>Intenta nuevamente.</p></div>';}
}

function heading(kicker,title,text,button=''){return `<header class="admin-heading"><div><span class="eyebrow">${kicker}</span><h1>${title}</h1>${text?`<p>${text}</p>`:''}</div>${button}</header>`;}

function openProductForm(product=null){
  const colorItems=(product?.product_colors||[]).slice().sort((a,b)=>a.sort_order-b.sort_order).map(c=>({...c}));
  const sizeItems=(product?.product_sizes||[]).slice().sort((a,b)=>a.sort_order-b.sort_order).map(s=>({...s}));
  const stockMap=new Map((product?.product_variants||[]).map(v=>{const color=colorItems.find(c=>c.id===v.color_id)?.name;const size=sizeItems.find(s=>s.id===v.size_id)?.name;return[`${color}|${size}`,v.stock];}));
  const form=document.createElement('form');form.className='admin-form';form.innerHTML=productFormMarkup(product,colorItems,sizeItems);
  const modal=openModal({title:product?'Editar producto':'Nuevo producto',content:form});
  const colorsRoot=form.querySelector('#admin-colors');const sizesRoot=form.querySelector('#admin-sizes');const matrix=form.querySelector('#variant-matrix');
  const renderOptions=()=>{colorsRoot.innerHTML=colorItems.map((item,index)=>`<div class="dynamic-row" data-index="${index}"><label>Color<input data-field="name" value="${escapeHtml(item.name)}" required></label><label>HEX<input data-field="hex_code" value="${escapeHtml(item.hex_code||'#18864B')}" pattern="#[0-9A-Fa-f]{6}"></label><button data-remove-color type="button" aria-label="Quitar color">×</button></div>`).join('');sizesRoot.innerHTML=sizeItems.map((item,index)=>`<div class="dynamic-row" data-index="${index}" style="grid-template-columns:1fr auto"><label>Talla<input data-field="name" value="${escapeHtml(item.name)}" required></label><button data-remove-size type="button" aria-label="Quitar talla">×</button></div>`).join('');renderMatrix();};
  const collectOptions=()=>{colorsRoot.querySelectorAll('.dynamic-row').forEach(row=>{const item=colorItems[Number(row.dataset.index)];item.name=row.querySelector('[data-field="name"]').value.trim();item.hex_code=row.querySelector('[data-field="hex_code"]').value.trim();});sizesRoot.querySelectorAll('.dynamic-row').forEach(row=>{sizeItems[Number(row.dataset.index)].name=row.querySelector('input').value.trim();});matrix.querySelectorAll('[data-stock]').forEach(input=>stockMap.set(input.dataset.stock,Math.max(0,Number(input.value)||0)));};
  const renderMatrix=()=>{if(!colorItems.length||!sizeItems.length){matrix.innerHTML='<p>Agrega al menos un color y una talla.</p>';return;}matrix.innerHTML=`<table class="variant-table"><thead><tr><th>Color / Talla</th>${sizeItems.map(s=>`<th>${escapeHtml(s.name)}</th>`).join('')}</tr></thead><tbody>${colorItems.map(c=>`<tr><th>${escapeHtml(c.name)}</th>${sizeItems.map(s=>`<td><input type="number" min="0" value="${stockMap.get(`${c.name}|${s.name}`)||0}" data-stock="${escapeHtml(`${c.name}|${s.name}`)}" aria-label="Stock ${escapeHtml(c.name)} ${escapeHtml(s.name)}"></td>`).join('')}</tr>`).join('')}</tbody></table>`;const select=form.querySelector('#image-color');select.innerHTML='<option value="">General / todos los colores</option>'+colorItems.map(c=>`<option value="${escapeHtml(c.name)}">${escapeHtml(c.name)}</option>`).join('');};
  form.querySelector('#add-color').addEventListener('click',()=>{collectOptions();colorItems.push({name:`Color ${colorItems.length+1}`,hex_code:'#18864B'});renderOptions();});
  form.querySelector('#add-size').addEventListener('click',()=>{collectOptions();sizeItems.push({name:`Talla ${sizeItems.length+1}`});renderOptions();});
  colorsRoot.addEventListener('click',event=>{const button=event.target.closest('[data-remove-color]');if(!button)return;collectOptions();colorItems.splice(Number(button.parentElement.dataset.index),1);renderOptions();});
  sizesRoot.addEventListener('click',event=>{const button=event.target.closest('[data-remove-size]');if(!button)return;collectOptions();sizeItems.splice(Number(button.parentElement.dataset.index),1);renderOptions();});
  colorsRoot.addEventListener('change',()=>{collectOptions();renderOptions();});sizesRoot.addEventListener('change',()=>{collectOptions();renderOptions();});
  form.querySelector('#product-files').addEventListener('change',event=>{form.querySelector('#new-image-previews').innerHTML=[...event.target.files].map(file=>`<div class="image-preview"><img src="${URL.createObjectURL(file)}" alt="${escapeHtml(file.name)}"></div>`).join('');});
  form.querySelectorAll('[data-delete-image]').forEach(button=>button.addEventListener('click',async()=>{if(!await confirmAction('¿Eliminar esta fotografía?','Eliminar foto'))return;try{await deleteRow('product_images',button.dataset.deleteImage);button.closest('.image-preview').remove();toast('Fotografía eliminada');}catch(error){console.error(error);toast('No pudimos eliminar la foto.','error');}}));
  form.querySelector('[data-preview-form]').addEventListener('click',()=>{const preview=collectProductValues(form);openModal({title:'Vista previa administrativa',content:`<article class="product-card" style="max-width:320px;margin:auto"><div class="product-card__media"><img src="${product?.product_images?.[0]?.url||'../assets/images/product-white.svg'}" alt="Vista previa"></div><div class="product-card__body"><div class="product-card__meta">${escapeHtml(teams.find(t=>t.id===preview.team_id)?.name||brands.find(b=>b.id===preview.brand_id)?.name||'Fuera de Lugar Sport')}</div><h3>${escapeHtml(preview.name||'Producto sin nombre')}</h3><div class="price"><strong>${formatMoney(preview.promo_price||preview.base_price)}</strong>${preview.promo_price?`<del>${formatMoney(preview.base_price)}</del>`:''}</div><p>${escapeHtml(preview.description||'')}</p><span class="status-pill status-pill--${preview.status}">${escapeHtml(preview.status)}</span></div></article>`});});
  form.addEventListener('submit',async event=>{event.preventDefault();collectOptions();if(!colorItems.length||!sizeItems.length){toast('Agrega al menos un color y una talla.','error');return;}const button=event.submitter;setButtonLoading(button,true,'Guardando…');try{const values=collectProductValues(form);for(const field of ['front_template_url','back_template_url','size_guide_image_url']){const file=form.querySelector(`[data-upload="${field}"]`)?.files[0];if(file)values[field]=await uploadImage('product-images',file,'templates');}let saved=await saveRow('products',values,product?.id);const categoryIds=[...form.querySelectorAll('[name="categoryIds"]:checked')].map(input=>input.value);const variants=[];matrix.querySelectorAll('[data-stock]').forEach(input=>{const[colorName,sizeName]=input.dataset.stock.split('|');variants.push({colorName,sizeName,stock:Number(input.value)||0,active:true});});const relation=await replaceProductRelations(saved.id,{categoryIds,colors:colorItems,sizes:sizeItems,variants});const files=[...form.querySelector('#product-files').files];if(files.length){const colorName=form.querySelector('#image-color').value;const colorId=relation.savedColors.find(c=>c.name===colorName)?.id||null;await saveProductImages(saved.id,files,colorId);}await refreshData();modal.close();loadSection(activeSection);toast('Producto guardado correctamente');}catch(error){console.error(error);toast('Hubo un problema al guardar los cambios. Revisa los datos.','error');setButtonLoading(button,false);}});
  renderOptions();
}

function productFormMarkup(p,colors,sizes){
  const val=(key,fallback='')=>escapeHtml(p?.[key]??fallback);const checked=key=>p?.[key]?'checked':'';
  return `<section class="admin-form__section"><h3>Información básica</h3><div class="form-grid"><label>Nombre<input name="name" value="${val('name')}" required maxlength="160"></label><label>Slug<input name="slug" value="${val('slug')}" placeholder="Se genera automáticamente"></label><label class="form-grid__full">Descripción<textarea name="description" rows="3">${val('description')}</textarea></label><label>Material<input name="material" value="${val('material')}"></label><label>Estado<select name="status"><option value="draft" ${p?.status==='draft'?'selected':''}>Borrador</option><option value="published" ${p?.status==='published'?'selected':''}>Publicado</option><option value="hidden" ${p?.status==='hidden'?'selected':''}>Oculto</option></select></label><label>Precio normal<input name="base_price" type="number" min="0" step="1000" value="${val('base_price',0)}" required></label><label>Marca<select name="brand_id"><option value="">Sin marca</option>${brands.map(item=>`<option value="${item.id}" ${p?.brand_id===item.id?'selected':''}>${escapeHtml(item.name)}</option>`).join('')}</select></label><label>Equipo<select name="team_id"><option value="">Sin equipo</option>${teams.map(item=>`<option value="${item.id}" ${p?.team_id===item.id?'selected':''}>${escapeHtml(item.name)}</option>`).join('')}</select></label><label class="check-field"><input name="featured" type="checkbox" ${checked('featured')}> Destacado en inicio</label></div></section>
  <section class="admin-form__section"><h3>Categorías</h3><div class="check-list">${categories.map(category=>`<label><input type="checkbox" name="categoryIds" value="${category.id}" ${p?.product_categories?.some(row=>row.category_id===category.id)?'checked':''}>${category.parent_id?'↳ ':''}${escapeHtml(category.name)}</label>`).join('')}</div></section>
  <section class="admin-form__section"><h3>Promoción</h3><div class="form-grid"><label>Precio promocional<input name="promo_price" type="number" min="0" step="1000" value="${val('promo_price')}"></label><label>Inicio<input name="promo_start" type="datetime-local" value="${toLocalInput(p?.promo_start)}"></label><label>Finalización<input name="promo_end" type="datetime-local" value="${toLocalInput(p?.promo_end)}"></label></div></section>
  <section class="admin-form__section"><h3>Colores y tallas</h3><div class="admin-panel__head"><strong>Colores</strong><button id="add-color" class="small-btn" type="button">+ Color</button></div><div id="admin-colors" class="dynamic-list"></div><div class="admin-panel__head" style="margin-top:1rem"><strong>Tallas</strong><button id="add-size" class="small-btn" type="button">+ Talla</button></div><div id="admin-sizes" class="dynamic-list"></div></section>
  <section class="admin-form__section"><h3>Inventario por variante</h3><p>Escribe el stock para cada combinación. Nunca se descuenta automáticamente.</p><div id="variant-matrix" style="overflow-x:auto"></div><div class="form-grid" style="margin-top:1rem"><label class="check-field"><input name="force_last_units" type="checkbox" ${checked('force_last_units')}> Marcar como últimas unidades</label><label class="check-field"><input name="force_sold_out" type="checkbox" ${checked('force_sold_out')}> Marcar como agotado</label></div></section>
  <section class="admin-form__section"><h3>Fotografías</h3>${p?.product_images?.length?`<div class="image-previews">${p.product_images.map(image=>`<div class="image-preview"><img src="${escapeHtml(image.url)}" alt="Foto"><button data-delete-image="${image.id}" type="button" aria-label="Eliminar foto">×</button></div>`).join('')}</div>`:''}<div class="upload-box"><label>Nuevas fotografías<input id="product-files" type="file" accept="image/jpeg,image/png,image/webp,image/avif" multiple></label><label>Relacionar con color<select id="image-color"><option value="">General / todos los colores</option></select></label><div id="new-image-previews" class="image-previews"></div></div></section>
  <section class="admin-form__section"><h3>Personalización y guía</h3><div class="form-grid"><label class="check-field"><input name="is_personalizable" type="checkbox" ${checked('is_personalizable')}> Permitir personalización</label><label>Precio personalización<input name="personalization_price" type="number" min="0" step="1000" value="${val('personalization_price',0)}"></label><label class="check-field"><input name="allow_name" type="checkbox" ${p?checked('allow_name'):'checked'}> Permitir nombre</label><label class="check-field"><input name="allow_number" type="checkbox" ${p?checked('allow_number'):'checked'}> Permitir número</label><label class="check-field"><input name="allow_logo" type="checkbox" ${checked('allow_logo')}> Permitir logo</label><label class="check-field"><input name="allow_font" type="checkbox" ${p?checked('allow_font'):'checked'}> Elegir fuente</label><label class="check-field"><input name="allow_text_color" type="checkbox" ${p?checked('allow_text_color'):'checked'}> Elegir color</label><label class="form-grid__full">Guía de tallas<textarea name="size_guide_text">${val('size_guide_text')}</textarea></label><input name="front_template_url" type="hidden" value="${val('front_template_url')}"><input name="back_template_url" type="hidden" value="${val('back_template_url')}"><input name="size_guide_image_url" type="hidden" value="${val('size_guide_image_url')}"><label>Plantilla frontal<input data-upload="front_template_url" type="file" accept="image/*"></label><label>Plantilla posterior<input data-upload="back_template_url" type="file" accept="image/*"></label><label>Imagen guía de tallas<input data-upload="size_guide_image_url" type="file" accept="image/*"></label></div></section>
  <div class="form-actions"><button class="btn btn--primary" type="submit">Guardar producto</button><button class="btn btn--ghost" data-preview-form type="button">Vista previa</button></div>`;
}

function collectProductValues(form){const data=new FormData(form);const nullable=value=>value||null;return{name:data.get('name').trim(),slug:data.get('slug').trim()||slugify(data.get('name')),description:nullable(data.get('description').trim()),material:nullable(data.get('material').trim()),base_price:Number(data.get('base_price')),promo_price:data.get('promo_price')?Number(data.get('promo_price')):null,promo_start:nullable(data.get('promo_start')?new Date(data.get('promo_start')).toISOString():null),promo_end:nullable(data.get('promo_end')?new Date(data.get('promo_end')).toISOString():null),status:data.get('status'),team_id:nullable(data.get('team_id')),brand_id:nullable(data.get('brand_id')),featured:data.has('featured'),is_personalizable:data.has('is_personalizable'),personalization_price:Number(data.get('personalization_price')||0),allow_name:data.has('allow_name'),allow_number:data.has('allow_number'),allow_logo:data.has('allow_logo'),allow_font:data.has('allow_font'),allow_text_color:data.has('allow_text_color'),force_last_units:data.has('force_last_units'),force_sold_out:data.has('force_sold_out'),size_guide_text:nullable(data.get('size_guide_text').trim()),front_template_url:nullable(data.get('front_template_url')),back_template_url:nullable(data.get('back_template_url')),size_guide_image_url:nullable(data.get('size_guide_image_url'))};}
function toLocalInput(value){if(!value)return'';const d=new Date(value);d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16);}

function renderDashboard(){
  const published=products.filter(product=>product.status==='published').length;
  const drafts=products.filter(product=>product.status==='draft').length;
  const sold=products.filter(isProductSoldOut).length;
  const low=products.filter(isProductLow).length;
  const promos=products.filter(isPromoActive).length;
  const attention=sold||low?`<section class="attention-panel" aria-labelledby="attention-title"><div class="attention-panel__head" id="attention-title"><span aria-hidden="true">!</span> Requiere atención</div><div class="attention-panel__links">${sold?`<button class="attention-link" data-go="stock" data-filter="out" type="button">${sold} ${sold===1?'producto agotado':'productos agotados'} →</button>`:''}${low?`<button class="attention-link" data-go="stock" data-filter="low" type="button">${low} ${low===1?'producto con stock bajo':'productos con stock bajo'} →</button>`:''}</div></section>`:'';
  $('#admin-content').innerHTML=heading('Panel administrador','Resumen','Lo importante de tu catálogo, de un vistazo.')+`<section class="stat-grid" aria-label="Estado del catálogo">${metricCard('Total productos',products.length,'products','','Ver catálogo')}${metricCard('Publicados',published,'products','success','Ver publicados','published')}${metricCard('Borradores',drafts,'products','','Revisar borradores','draft')}${metricCard('Últimas unidades',low,'stock','warning','Revisar stock','low')}${metricCard('Agotados',sold,'stock','danger','Reponer stock','out')}${metricCard('Promociones activas',promos,'promotions','success','Ver promociones')}</section>${attention}<section class="admin-panel"><div class="admin-panel__head"><h2>Acciones rápidas</h2></div><div class="quick-actions"><button class="quick-action" data-quick="new-product" type="button"><span class="quick-action__icon">+</span><span>Nuevo producto</span></button><button class="quick-action" data-go="stock" type="button"><span class="quick-action__icon">↕</span><span>Actualizar stock</span></button><button class="quick-action" data-quick="new-category" type="button"><span class="quick-action__icon">◇</span><span>Nueva categoría</span></button><button class="quick-action" data-go="promotions" type="button"><span class="quick-action__icon">%</span><span>Gestionar promociones</span></button></div></section><section class="admin-panel"><div class="admin-panel__head"><h2>Actualizados recientemente</h2><button class="admin-section-link" data-go="products" type="button">Ver todos →</button></div>${productRows(products.slice(0,6))}</section>`;
  $$('[data-go]').forEach(button=>button.addEventListener('click',()=>navigateTo(button.dataset.go,button.dataset.filter?{status:button.dataset.filter}:{})));
  $('[data-quick="new-product"]').addEventListener('click',()=>{navigateTo('products');openProductForm();});
  $('[data-quick="new-category"]').addEventListener('click',()=>{navigateTo('categories');openEntityForm('categories');});
  bindProductRowActions(renderDashboard);
}

function metricCard(label,value,section,tone='',action='',status=''){return `<button class="stat-card ${tone?`stat-card--${tone}`:''}" data-go="${section}" ${status?`data-filter="${status}"`:''} type="button"><span>${label}</span><strong>${value}</strong><small>${action} →</small></button>`;}

function renderProducts(){
  const params=new URLSearchParams(location.search);
  const state={search:params.get('search')||'',status:params.get('status')||'all',category:params.get('category')||'',team:params.get('team')||'',brand:params.get('brand')||'',page:Math.max(1,Number(params.get('page'))||1)};
  if(!['all','published','draft','hidden'].includes(state.status))state.status='all';
  $('#admin-content').innerHTML=heading('Catálogo','Productos','Encuentra, publica y edita productos sin perder contexto.','<button id="new-product" class="btn btn--primary" type="button">+ Nuevo producto</button>')+`<section class="admin-panel"><div class="admin-panel__head"><h2>Catálogo</h2><p>${products.length} productos registrados</p></div><div class="admin-toolbar"><div class="admin-search-wrap"><input id="admin-product-search" class="admin-search" type="search" value="${escapeHtml(state.search)}" placeholder="Buscar por nombre, equipo o marca" aria-label="Buscar productos"></div><button id="product-filters-button" class="toolbar-button" type="button" aria-expanded="false" aria-controls="product-filter-panel">Filtros</button><div class="admin-chips" role="group" aria-label="Filtrar por estado"><button class="filter-chip ${state.status==='all'?'active':''}" data-product-status="all" type="button">Todos</button><button class="filter-chip ${state.status==='published'?'active':''}" data-product-status="published" type="button">Publicados</button><button class="filter-chip ${state.status==='draft'?'active':''}" data-product-status="draft" type="button">Borradores</button><button class="filter-chip ${state.status==='hidden'?'active':''}" data-product-status="hidden" type="button">Ocultos</button></div><div id="product-filter-panel" class="filter-panel" hidden>${selectFilter('product-category','Categoría',categories,state.category)}${selectFilter('product-team','Equipo',teams,state.team)}${selectFilter('product-brand','Marca',brands,state.brand)}<div class="filter-panel__wide"><button id="clear-product-filters" class="small-btn" type="button">Limpiar filtros</button></div></div></div><div id="admin-product-results"></div></section>`;
  const renderResults=()=>{
    const filtered=products.filter(product=>{const haystack=cleanText([product.name,product.teams?.name,product.brands?.name].join(' '));return(!state.search||haystack.includes(cleanText(state.search)))&&(state.status==='all'||product.status===state.status)&&(!state.category||product.product_categories.some(row=>row.category_id===state.category))&&(!state.team||product.team_id===state.team)&&(!state.brand||product.brand_id===state.brand);});
    const pages=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE));state.page=Math.min(state.page,pages);const visible=filtered.slice((state.page-1)*PAGE_SIZE,state.page*PAGE_SIZE);
    $('#admin-product-results').innerHTML=`<div class="results-meta"><span>${filtered.length} ${filtered.length===1?'resultado':'resultados'}</span></div>${visible.length?productRows(visible):emptyMarkup('No encontramos productos','Prueba otra búsqueda o limpia los filtros.')}${paginationMarkup(state.page,pages)}`;
    bindProductRowActions(renderProducts);bindPagination($('#admin-product-results'),state,pages,renderResults);syncSectionUrl('products',state);
  };
  $('#new-product').addEventListener('click',()=>openProductForm());
  $('#product-filters-button').addEventListener('click',event=>{const panel=$('#product-filter-panel');panel.hidden=!panel.hidden;event.currentTarget.setAttribute('aria-expanded',String(!panel.hidden));});
  $$('[data-product-status]').forEach(button=>button.addEventListener('click',()=>{state.status=button.dataset.productStatus;state.page=1;$$('[data-product-status]').forEach(item=>item.classList.toggle('active',item===button));renderResults();}));
  const search=debounce(value=>{state.search=value;state.page=1;renderResults();});$('#admin-product-search').addEventListener('input',event=>search(event.target.value));
  [['#product-category','category'],['#product-team','team'],['#product-brand','brand']].forEach(([selector,key])=>$(selector).addEventListener('change',event=>{state[key]=event.target.value;state.page=1;renderResults();}));
  $('#clear-product-filters').addEventListener('click',()=>navigateTo('products'));renderResults();
}

function selectFilter(id,label,items,value){return `<label>${label}<select id="${id}"><option value="">Todos</option>${items.map(item=>`<option value="${item.id}" ${value===item.id?'selected':''}>${escapeHtml(item.name)}</option>`).join('')}</select></label>`;}
function syncSectionUrl(section,state){const query=new URLSearchParams({section});Object.entries(state).forEach(([key,value])=>{if(value&&value!=='all'&&!(key==='page'&&value===1))query.set(key,value);});history.replaceState({},'',`${location.pathname}?${query}`);}
function paginationMarkup(page,pages){if(pages<=1)return'';return `<nav class="pagination" aria-label="Paginación"><button data-page="${page-1}" ${page===1?'disabled':''} type="button">← Anterior</button><span>Página ${page} de ${pages}</span><button data-page="${page+1}" ${page===pages?'disabled':''} type="button">Siguiente →</button></nav>`;}
function bindPagination(root,state,pages,render){root.querySelectorAll('[data-page]').forEach(button=>button.addEventListener('click',()=>{state.page=Math.min(pages,Math.max(1,Number(button.dataset.page)));render();root.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});}));}
function emptyMarkup(title,text){return `<div class="empty-state empty-state--admin"><h3>${title}</h3><p>${text}</p></div>`;}
function formatUpdated(value){const date=new Date(value);const diff=Math.floor((Date.now()-date.getTime())/86400000);if(diff<=0)return'hoy';if(diff===1)return'ayer';if(diff<7)return`hace ${diff} días`;return date.toLocaleDateString('es-CO',{day:'numeric',month:'short'});}

function productRows(items){return `<div class="data-list">${items.map(product=>`<article class="data-row" data-product="${product.id}"><div class="data-row__thumb"><img src="${escapeHtml(productImage(product))}" alt="" loading="lazy" width="52" height="52"></div><div class="data-row__main"><strong>${escapeHtml(product.name)}</strong><small>${formatMoney(currentPrice(product))} · Actualizado ${formatUpdated(product.updated_at)}</small></div><span class="status-pill status-pill--${product.status}">${product.status==='published'?'Publicado':product.status==='hidden'?'Oculto':'Borrador'}</span><div class="data-row__actions"><button class="small-btn" data-edit type="button">Editar</button><details class="action-menu"><summary aria-label="Más acciones">⋮</summary><div class="action-menu__popover"><button data-preview type="button">Vista previa</button><button data-toggle type="button">${product.status==='published'?'Ocultar':'Publicar'}</button><button data-delete type="button">Eliminar</button></div></details></div></article>`).join('')}</div>`;}

function bindProductRowActions(afterChange=renderProducts){
  $$('.data-row[data-product]').forEach(row=>{const product=products.find(item=>item.id===row.dataset.product);if(!product)return;
    row.querySelector('[data-preview]')?.addEventListener('click',()=>window.open(`../producto.html?slug=${encodeURIComponent(product.slug)}`,'_blank','noopener'));
    row.querySelector('[data-edit]')?.addEventListener('click',()=>openProductForm(product));
    row.querySelector('[data-toggle]')?.addEventListener('click',async event=>{event.currentTarget.disabled=true;try{await saveRow('products',{status:product.status==='published'?'hidden':'published'},product.id);await refreshData();afterChange();toast('Estado actualizado');}catch(error){console.error(error);event.currentTarget.disabled=false;toast('No pudimos cambiar el estado.','error');}});
    row.querySelector('[data-delete]')?.addEventListener('click',async()=>{if(!await confirmAction(`¿Eliminar “${product.name}”? Esta acción también elimina sus variantes e imágenes registradas.`,'Eliminar producto'))return;try{await deleteRow('products',product.id);await refreshData();afterChange();toast('Producto eliminado');}catch(error){console.error(error);toast('No pudimos eliminar el producto.','error');}});
  });
}

function renderStock(){
  const params=new URLSearchParams(location.search);
  const allVariants=products.flatMap(product=>product.product_variants.map(variant=>({...variant,product,color:product.product_colors.find(color=>color.id===variant.color_id)?.name||'Sin color',size:product.product_sizes.find(size=>size.id===variant.size_id)?.name||'Talla única'})));
  const colors=[...new Set(allVariants.map(variant=>variant.color))].sort((a,b)=>a.localeCompare(b));const sizes=[...new Set(allVariants.map(variant=>variant.size))];
  const state={search:params.get('search')||'',status:['all','low','out','available'].includes(params.get('status'))?params.get('status'):'all',category:params.get('category')||'',team:params.get('team')||'',brand:params.get('brand')||'',color:params.get('color')||'',size:params.get('size')||'',sort:params.get('sort')||'name',page:Math.max(1,Number(params.get('page'))||1)};
  $('#admin-content').innerHTML=heading('Inventario','Stock rápido',`${allVariants.length} variantes · ${products.length} productos. Los pedidos por WhatsApp no descuentan stock.`)+`<section class="admin-panel"><div class="admin-toolbar admin-toolbar--sticky"><div class="admin-search-wrap"><input id="stock-search-v2" class="admin-search" type="search" value="${escapeHtml(state.search)}" placeholder="Producto, color, talla, equipo…" aria-label="Buscar en el inventario"></div><button id="stock-filters-button" class="toolbar-button" type="button" aria-expanded="false" aria-controls="stock-filter-panel">Filtros <span id="stock-filter-count"></span></button><div class="admin-chips" role="group" aria-label="Filtrar por disponibilidad"><button class="filter-chip ${state.status==='all'?'active':''}" data-stock-status="all" type="button">Todos</button><button class="filter-chip ${state.status==='low'?'active':''}" data-stock-status="low" type="button">Últimas unidades</button><button class="filter-chip ${state.status==='out'?'active':''}" data-stock-status="out" type="button">Agotados</button><button class="filter-chip ${state.status==='available'?'active':''}" data-stock-status="available" type="button">Disponibles</button></div><div id="stock-filter-panel" class="filter-panel" hidden>${selectFilter('stock-category','Categoría',categories,state.category)}${selectFilter('stock-team','Equipo',teams,state.team)}${selectFilter('stock-brand','Marca',brands,state.brand)}${selectTextFilter('stock-color','Color',colors,state.color)}${selectTextFilter('stock-size','Talla',sizes,state.size)}<label>Orden<select id="stock-sort"><option value="name" ${state.sort==='name'?'selected':''}>A–Z</option><option value="stock-asc" ${state.sort==='stock-asc'?'selected':''}>Menor stock</option><option value="stock-desc" ${state.sort==='stock-desc'?'selected':''}>Mayor stock</option><option value="updated" ${state.sort==='updated'?'selected':''}>Actualizados recientemente</option></select></label><div class="filter-panel__wide"><button id="clear-stock-filters" class="small-btn" type="button">Limpiar filtros</button></div></div></div><div id="stock-results-v2"></div></section>`;
  const renderResults=()=>{
    const query=cleanText(state.search);const queryWords=query.split(/\s+/).filter(Boolean);let groups=products.map(product=>{const productVariants=allVariants.filter(variant=>variant.product.id===product.id);const productHaystack=cleanText([product.name,product.teams?.name,product.brands?.name,...product.product_categories.map(row=>row.categories?.name)].join(' '));let matchingVariants=productVariants.filter(variant=>queryWords.every(word=>cleanText(`${productHaystack} ${variant.color} ${variant.size}`).includes(word)));matchingVariants=matchingVariants.filter(variant=>{const status=stockStatus(variant.stock,product).className;return(state.status==='all'||state.status===status||(state.status==='out'&&status==='sold'))&&(!state.color||variant.color===state.color)&&(!state.size||variant.size===state.size);});return{product,variants:matchingVariants,autoOpen:Boolean(query)||state.status!=='all'};}).filter(group=>group.variants.length&&(!state.category||group.product.product_categories.some(row=>row.category_id===state.category))&&(!state.team||group.product.team_id===state.team)&&(!state.brand||group.product.brand_id===state.brand));
    const updatedAt=group=>Math.max(new Date(group.product.updated_at).getTime(),...group.variants.map(variant=>new Date(variant.updated_at||0).getTime()));groups.sort((a,b)=>state.sort==='stock-asc'?totalStock(a.product)-totalStock(b.product):state.sort==='stock-desc'?totalStock(b.product)-totalStock(a.product):state.sort==='updated'?updatedAt(b)-updatedAt(a):a.product.name.localeCompare(b.product.name));
    const pages=Math.max(1,Math.ceil(groups.length/STOCK_PAGE_SIZE));state.page=Math.min(state.page,pages);const visible=groups.slice((state.page-1)*STOCK_PAGE_SIZE,state.page*STOCK_PAGE_SIZE);const variantCount=groups.reduce((sum,group)=>sum+group.variants.length,0);
    $('#stock-results-v2').innerHTML=`<div class="results-meta"><span>${groups.length} ${groups.length===1?'producto':'productos'} · ${variantCount} ${variantCount===1?'variante':'variantes'}</span><button id="toggle-stock-groups" type="button">${visible.some(group=>!group.autoOpen)?'Expandir resultados':'Contraer resultados'}</button></div>${visible.length?`<div class="stock-products">${visible.map(stockGroupMarkup).join('')}</div>`:emptyMarkup('No encontramos variantes','Prueba otra búsqueda o limpia los filtros.')}${paginationMarkup(state.page,pages)}`;
    bindStockControls(allVariants);bindPagination($('#stock-results-v2'),state,pages,renderResults);$('#toggle-stock-groups')?.addEventListener('click',event=>{const details=$$('#stock-results-v2 .stock-product');const open=details.some(item=>!item.open);details.forEach(item=>item.open=open);event.currentTarget.textContent=open?'Contraer resultados':'Expandir resultados';});updateStockFilterCount(state);syncSectionUrl('stock',state);
  };
  $('#stock-filters-button').addEventListener('click',event=>{const panel=$('#stock-filter-panel');panel.hidden=!panel.hidden;event.currentTarget.setAttribute('aria-expanded',String(!panel.hidden));});
  $$('[data-stock-status]').forEach(button=>button.addEventListener('click',()=>{state.status=button.dataset.stockStatus;state.page=1;$$('[data-stock-status]').forEach(item=>item.classList.toggle('active',item===button));renderResults();}));
  const search=debounce(value=>{state.search=value;state.page=1;renderResults();});$('#stock-search-v2').addEventListener('input',event=>search(event.target.value));
  [['#stock-category','category'],['#stock-team','team'],['#stock-brand','brand'],['#stock-color','color'],['#stock-size','size'],['#stock-sort','sort']].forEach(([selector,key])=>$(selector).addEventListener('change',event=>{state[key]=event.target.value;state.page=1;renderResults();}));
  $('#clear-stock-filters').addEventListener('click',()=>navigateTo('stock'));renderResults();
}

function selectTextFilter(id,label,items,value){return `<label>${label}<select id="${id}"><option value="">Todos</option>${items.map(item=>`<option value="${escapeHtml(item)}" ${value===item?'selected':''}>${escapeHtml(item)}</option>`).join('')}</select></label>`;}
function updateStockFilterCount(state){const count=['category','team','brand','color','size'].filter(key=>state[key]).length+(state.status!=='all'?1:0);$('#stock-filter-count').textContent=count?`(${count})`:'';}
function stockGroupMarkup(group){const sold=group.variants.filter(variant=>stockStatus(variant.stock,variant.product).className==='sold').length;const low=group.variants.filter(variant=>stockStatus(variant.stock,variant.product).className==='low').length;return `<details class="stock-product" data-stock-product="${group.product.id}" ${group.autoOpen?'open':''}><summary><span class="stock-product__thumb"><img src="${escapeHtml(productImage(group.product))}" alt="" loading="lazy" width="50" height="54"></span><span class="stock-product__copy"><strong>${escapeHtml(group.product.name)}</strong><small>${group.product.product_variants.length} variantes · ${totalStock(group.product)} unidades</small>${sold||low?`<span class="stock-product__alerts">${sold?`<span class="sold">${sold} agotada${sold===1?'':'s'}</span>`:''}${low?`<span>${low} con stock bajo</span>`:''}</span>`:''}</span><span class="stock-product__chevron" aria-hidden="true">⌄</span></summary><div class="stock-variants">${group.variants.map(stockRowMarkup).join('')}</div></details>`;}
function stockRowMarkup(variant){const status=stockStatus(variant.stock,variant.product);return `<article class="stock-row" data-variant="${variant.id}"><div class="stock-row__info"><strong>${escapeHtml(variant.color)} / ${escapeHtml(variant.size)}</strong><span class="status-pill status-pill--${status.className}" data-stock-pill>${status.label}</span></div><div class="stock-row__actions"><div class="stock-control"><button data-minus type="button" aria-label="Restar una unidad">−</button><input type="number" min="0" step="1" inputmode="numeric" value="${variant.stock}" aria-label="Stock de ${escapeHtml(variant.color)} talla ${escapeHtml(variant.size)}"><button data-plus type="button" aria-label="Sumar una unidad">+</button></div><span class="stock-save-state" data-save-state aria-live="polite"></span></div></article>`;}

function bindStockControls(variants){
  $$('.stock-row[data-variant]').forEach(row=>{const variant=variants.find(item=>item.id===row.dataset.variant);const input=row.querySelector('input');const controls=[row.querySelector('[data-minus]'),row.querySelector('[data-plus]')];const stateLabel=row.querySelector('[data-save-state]');let saving=false;
    const paint=value=>{const status=stockStatus(value,variant.product);const pill=row.querySelector('[data-stock-pill]');pill.className=`status-pill status-pill--${status.className}`;pill.textContent=status.label;refreshStockGroupSummary(row,variant.product);};
    const save=async raw=>{if(saving)return;const parsed=Number(raw);if(!Number.isInteger(parsed)||parsed<0){input.value=variant.stock;toast('El stock debe ser un número entero desde 0.','error');return;}if(parsed===variant.stock)return;const previous=variant.stock;saving=true;variant.stock=parsed;input.value=parsed;paint(parsed);controls.forEach(button=>button.disabled=true);input.disabled=true;stateLabel.className='stock-save-state stock-save-state--saving';stateLabel.textContent='Guardando…';try{await saveRow('product_variants',{stock:parsed},variant.id);stateLabel.className='stock-save-state stock-save-state--saved';stateLabel.textContent='✓ Guardado';setTimeout(()=>{if(stateLabel.textContent==='✓ Guardado')stateLabel.textContent='';},1800);}catch(error){console.error(error);variant.stock=previous;input.value=previous;paint(previous);stateLabel.className='stock-save-state stock-save-state--error';stateLabel.textContent='Error al guardar';toast('No pudimos actualizar el stock. Se restauró el valor anterior.','error');}finally{saving=false;controls.forEach(button=>button.disabled=false);input.disabled=false;}};
    row.querySelector('[data-minus]').addEventListener('click',()=>save(Math.max(0,Number(input.value)-1)));row.querySelector('[data-plus]').addEventListener('click',()=>save(Number(input.value)+1));input.addEventListener('keydown',event=>{if(['-','+','.','e','E'].includes(event.key))event.preventDefault();if(event.key==='Enter'){event.preventDefault();input.blur();}});input.addEventListener('blur',()=>save(input.value));
  });
}

function refreshStockGroupSummary(row,product){const copy=row.closest('.stock-product')?.querySelector('.stock-product__copy');if(!copy)return;copy.querySelector('small').textContent=`${product.product_variants.length} variantes · ${totalStock(product)} unidades`;const statuses=product.product_variants.map(variant=>stockStatus(variant.stock,product).className);const sold=statuses.filter(status=>status==='sold').length;const low=statuses.filter(status=>status==='low').length;let alerts=copy.querySelector('.stock-product__alerts');if(!sold&&!low){alerts?.remove();return;}if(!alerts){alerts=document.createElement('span');alerts.className='stock-product__alerts';copy.append(alerts);}alerts.innerHTML=`${sold?`<span class="sold">${sold} agotada${sold===1?'':'s'}</span>`:''}${low?`<span>${low} con stock bajo</span>`:''}`;}

function entityLoadingMarkup(){return `<section class="admin-skeleton" aria-label="Cargando registros" aria-busy="true"><span class="skeleton-block skeleton-block--title"></span><span class="skeleton-block skeleton-block--search"></span>${Array.from({length:5},()=>'<span class="skeleton-block skeleton-block--row"></span>').join('')}</section>`;}

function getEntityConfig(type){
  return {
    categories:{title:'Categorías',singular:'categoría',plural:'categorías',items:categories,button:'Nueva categoría',placeholder:'Buscar categoría o subcategoría',quickKey:'status',quickOptions:[['all','Todas'],['active','Activas'],['inactive','Inactivas']],kindOptions:[['all','Todas'],['parent','Categorías principales'],['child','Subcategorías']]},
    teams:{title:'Equipos',singular:'equipo',plural:'equipos',items:teams,button:'Nuevo equipo',placeholder:'Buscar equipo…',quickKey:'kind',quickOptions:[['all','Todos'],['club','Clubes'],['national_team','Selecciones'],['colombian_team','Colombianos']],kindOptions:[['all','Todos'],['club','Clubes'],['national_team','Selecciones'],['colombian_team','Equipos colombianos']]},
    brands:{title:'Marcas',singular:'marca',plural:'marcas',items:brands,button:'Nueva marca',placeholder:'Buscar marca…',quickKey:'status',quickOptions:[['all','Todas'],['active','Activas'],['inactive','Inactivas']],kindOptions:[]}
  }[type];
}

function getEntityState(type){
  const params=new URLSearchParams(location.search);const state={search:params.get('search')||'',status:params.get('status')||'all',kind:params.get('kind')||'all',sort:params.get('sort')||'az',page:Math.max(1,Number(params.get('page'))||1),parent:type==='categories'?(params.get('parent')||''):''};
  if(!['all','active','inactive'].includes(state.status))state.status='all';
  const allowedKinds=type==='categories'?['all','parent','child']:type==='teams'?['all','club','national_team','colombian_team']:['all'];if(!allowedKinds.includes(state.kind))state.kind='all';
  if(!['az','za','newest','oldest'].includes(state.sort))state.sort='az';return state;
}

function entityKindLabel(type,item){
  if(type==='categories')return item.parent_id?'Subcategoría':'Categoría principal';
  if(type==='brands')return'Marca';
  return {club:'Club',national_team:'Selección',colombian_team:'Equipo colombiano'}[item.type]||'Equipo';
}

function entitySortOptions(value){return `<option value="az" ${value==='az'?'selected':''}>A–Z</option><option value="za" ${value==='za'?'selected':''}>Z–A</option><option value="newest" ${value==='newest'?'selected':''}>Más recientes</option><option value="oldest" ${value==='oldest'?'selected':''}>Más antiguos</option>`;}

function entityFilterPanel(type,config,state){
  const kind=config.kindOptions.length?`<label>Tipo<select data-entity-filter="kind">${config.kindOptions.map(([value,label])=>`<option value="${value}" ${state.kind===value?'selected':''}>${label}</option>`).join('')}</select></label>`:'';const feminine=type!=='teams';
  return `<div id="entity-filter-panel" class="filter-panel entity-filter-panel" hidden><label>Estado<select data-entity-filter="status"><option value="all" ${state.status==='all'?'selected':''}>${feminine?'Todas':'Todos'}</option><option value="active" ${state.status==='active'?'selected':''}>${feminine?'Activas':'Activos'}</option><option value="inactive" ${state.status==='inactive'?'selected':''}>${feminine?'Inactivas':'Inactivos'}</option></select></label>${kind}<label class="entity-filter-sort">Orden<select data-entity-filter="sort">${entitySortOptions(state.sort)}</select></label><div class="filter-panel__wide"><button class="small-btn" data-clear-entities type="button">Limpiar filtros</button></div></div>`;
}

function entityToolbar(type,config,state){
  const quickLabel=config.quickKey==='status'?'Filtrar por estado':'Filtrar por tipo';
  return `<div class="entity-toolbar"><div class="entity-toolbar__sticky"><div class="admin-search-wrap"><input id="entity-search" class="admin-search" type="search" value="${escapeHtml(state.search)}" placeholder="${escapeHtml(config.placeholder)}" aria-label="${escapeHtml(config.placeholder)}" autocomplete="off"></div><button id="entity-filters-button" class="toolbar-button" type="button" aria-expanded="false" aria-controls="entity-filter-panel">Filtros <span id="entity-filter-count"></span></button><label class="entity-sort">Ordenar<span class="sr-only"> registros</span><select data-entity-filter="sort">${entitySortOptions(state.sort)}</select></label></div><div class="admin-chips" role="group" aria-label="${quickLabel}">${config.quickOptions.map(([value,label])=>`<button class="filter-chip ${state[config.quickKey]===value?'active':''}" data-entity-quick="${value}" type="button">${label}</button>`).join('')}</div>${entityFilterPanel(type,config,state)}</div>`;
}

function sortEntityItems(items,state){
  const direction=state.sort==='za'?-1:1;const byName=(a,b)=>a.name.localeCompare(b.name,'es',{sensitivity:'base'})*direction;const byDate=(a,b)=>(new Date(a.created_at||0)-new Date(b.created_at||0))*(state.sort==='newest'?-1:1);
  return items.slice().sort(state.sort==='newest'||state.sort==='oldest'?byDate:byName);
}

function orderEntityItems(type,items,state){
  if(state.search){const query=cleanText(state.search);return sortEntityItems(items,state).sort((a,b)=>{const score=item=>{const name=cleanText(item.name);const slug=cleanText(item.slug);if(name===query)return 5;if(name.startsWith(query))return 4;if(name.includes(query))return 3;if(slug.includes(query))return 2;return 1;};return score(b)-score(a);});}
  if(type!=='categories'||state.kind!=='all'||state.parent)return sortEntityItems(items,state);
  const available=new Set(items.map(item=>item.id));const roots=sortEntityItems(items.filter(item=>!item.parent_id||!available.has(item.parent_id)),state);const ordered=[];const seen=new Set();
  roots.forEach(root=>{ordered.push(root);seen.add(root.id);sortEntityItems(items.filter(item=>item.parent_id===root.id),state).forEach(child=>{ordered.push(child);seen.add(child.id);});});
  ordered.push(...sortEntityItems(items.filter(item=>!seen.has(item.id)),state));return ordered;
}

function entityMatches(type,item,state){
  const parent=type==='categories'?categories.find(category=>category.id===item.parent_id):null;const searchable=[item.name,item.slug,parent?.name,type==='teams'?entityKindLabel(type,item):''].filter(Boolean).join(' ');const words=cleanText(state.search).split(/\s+/).filter(Boolean);
  return words.every(word=>cleanText(searchable).includes(word))&&(state.status==='all'||(state.status==='active')===Boolean(item.active))&&(state.kind==='all'||(type==='categories'?(state.kind==='parent'?!item.parent_id:Boolean(item.parent_id)):item.type===state.kind))&&(!state.parent||item.parent_id===state.parent);
}

function entityAssetUrl(type,item){return type==='categories'?item?.image_url:type==='teams'?item?.crest_url:item?.logo_url;}

function entityThumb(type,item){
  const url=entityAssetUrl(type,item);const initials=type==='categories'?categoryInitials(item.name):item.name.split(/\s+/).slice(0,2).map(word=>word[0]).join('').toUpperCase();
  return `<div class="data-row__thumb entity-thumb ${type==='categories'?'entity-thumb--category':''}">${url?`<img src="${escapeHtml(localAsset(url))}" alt="" loading="lazy" width="52" height="52">`:`<span aria-hidden="true">${escapeHtml(initials)}</span>`}</div>`;
}

function entityProductCount(type,item){return type==='categories'?products.filter(product=>product.product_categories.some(row=>row.category_id===item.id)).length:type==='teams'?products.filter(product=>product.team_id===item.id).length:products.filter(product=>product.brand_id===item.id).length;}

function entityRows(type,items,{hierarchical=false,expandedParents=new Set(),childCounts=new Map()}={}){
  return `<div class="data-list entity-list ${hierarchical?'category-tree':''}">${items.map(item=>{const parent=type==='categories'?categories.find(category=>category.id===item.parent_id):null;const productCount=entityProductCount(type,item);const childCount=hierarchical&&!parent?Number(childCounts.get(item.id)||0):0;const expanded=childCount>0&&expandedParents.has(item.id);const detail=type==='categories'?(parent?`${parent.name} · slug: ${item.slug}`:`Categoría principal · slug: ${item.slug}`):`${entityKindLabel(type,item)} · slug: ${item.slug}`;const nameMarkup=hierarchical&&!parent&&childCount?`<button class="category-tree-toggle" data-toggle-category="${item.id}" type="button" aria-expanded="${expanded}" aria-label="${expanded?'Ocultar':'Mostrar'} ${childCount} ${childCount===1?'subcategoría':'subcategorías'} de ${escapeHtml(item.name)}"><span class="category-tree-toggle__chevron" aria-hidden="true">›</span><strong>${escapeHtml(item.name)}</strong><span class="category-tree-count">${childCount} ${childCount===1?'subcategoría':'subcategorías'}</span></button>`:`<strong>${parent?'<span class="entity-branch" aria-hidden="true">↳</span>':''}${escapeHtml(item.name)}</strong>${hierarchical&&!parent?'<span class="category-tree-count category-tree-count--empty">Sin subcategorías</span>':''}`;return `<article class="data-row entity-row ${parent?'entity-row--child':'entity-row--parent'} ${expanded?'entity-row--expanded':''}" data-entity-id="${item.id}" ${parent?`data-parent-id="${parent.id}"`:''}>${entityThumb(type,item)}<div class="data-row__main">${nameMarkup}<small>${escapeHtml(detail)}</small>${productCount?`<span class="entity-related-count">${productCount} ${productCount===1?'producto asociado':'productos asociados'}</span>`:''}</div><span class="status-pill status-pill--${item.active?'active':'hidden'}">${item.active?'Activo':'Inactivo'}</span><div class="data-row__actions"><button class="small-btn" data-edit data-edit-entity type="button">Editar</button><details class="action-menu"><summary aria-label="Más acciones para ${escapeHtml(item.name)}">⋮</summary><div class="action-menu__popover" role="menu"><button data-edit-entity type="button" role="menuitem">Editar</button>${productCount?'<button data-view-related type="button" role="menuitem">Ver productos</button>':''}<button data-delete-entity type="button" role="menuitem">Eliminar</button></div></details></div></article>`;}).join('')}</div>`;
}

function entityEmptyMarkup(config,state){
  if(!config.items.length)return `<div class="empty-state empty-state--admin entity-empty"><h3>No hay ${config.plural} todavía.</h3><p>Crea el primer registro para comenzar.</p><button class="btn btn--primary" data-create-entity type="button">+ ${config.button}</button></div>`;
  const query=state.search.trim();const title=query?`No encontramos ${config.plural} con “${escapeHtml(query)}”.`:`No encontramos ${config.plural} con estos filtros.`;return `<div class="empty-state empty-state--admin entity-empty"><h3>${title}</h3><p>Prueba otra búsqueda o vuelve a mostrar todos los registros.</p><button class="btn btn--ghost" data-clear-entities type="button">Limpiar búsqueda y filtros</button></div>`;
}

function updateEntityControls(config,state){
  $$('[data-entity-quick]').forEach(button=>button.classList.toggle('active',button.dataset.entityQuick===state[config.quickKey]));$$('[data-entity-filter]').forEach(select=>{select.value=state[select.dataset.entityFilter];});
  const count=(state.status!=='all'?1:0)+(state.kind!=='all'?1:0)+(state.parent?1:0);$('#entity-filter-count').textContent=count?`(${count})`:'';
}

function relatedProductParams(type,item){return type==='categories'?{category:item.id}:type==='teams'?{team:item.id}:{brand:item.id};}

function showEntityDependency(type,item,dependencies,trigger=null){
  const config=getEntityConfig(type);const children=Number(dependencies.child_count||0);const related=Number(dependencies.product_count||0);const wrapper=document.createElement('div');wrapper.className='dependency-dialog';const messages=[];
  if(children)messages.push(`Esta categoría contiene ${children} ${children===1?'subcategoría':'subcategorías'}. Primero debes moverlas o eliminarlas.`);if(related)messages.push(type==='brands'?`La marca “${item.name}” está asociada a ${related} ${related===1?'producto':'productos'}.`:`No puedes eliminar “${item.name}” porque tiene ${related} ${related===1?'producto asociado':'productos asociados'}.`);
  wrapper.innerHTML=`${messages.map(message=>`<p>${escapeHtml(message)}</p>`).join('')}<p class="dependency-dialog__hint">Si solo quieres dejar de mostrar ${type==='categories'?'esta categoría':type==='teams'?'este equipo':'esta marca'} en la tienda, puedes ${type==='teams'?'desactivarlo':'desactivarla'} en lugar de ${type==='teams'?'eliminarlo':'eliminarla'}.</p><div class="form-actions">${children?'<button class="btn btn--primary" data-view-children type="button">Ver subcategorías</button>':''}${related?`<button class="btn btn--primary" data-view-products type="button">Ver ${related} ${related===1?'producto':'productos'}</button>`:''}<button class="btn btn--ghost" data-close-dependency type="button">${children&&!related?'Entendido':'Cancelar'}</button></div>`;
  const modal=openModal({title:`No puedes eliminar ${type==='teams'?'este':'esta'} ${config.singular} todavía`,content:wrapper,trigger});
  wrapper.querySelector('[data-close-dependency]').addEventListener('click',()=>modal.close());wrapper.querySelector('[data-view-children]')?.addEventListener('click',()=>{modal.close();navigateTo('categories',{parent:item.id});});wrapper.querySelector('[data-view-products]')?.addEventListener('click',()=>{modal.close();navigateTo('products',relatedProductParams(type,item));});
}

async function requestEntityDeletion(type,item,trigger){
  const config=getEntityConfig(type);const article=type==='teams'?'el':'la';trigger.disabled=true;let dependencies;
  try{dependencies=await getCatalogEntityDependencies(type,item.id);}catch(error){console.error(error);toast(`No pudimos comprobar si ${article} ${config.singular} puede eliminarse. Intenta nuevamente.`,'error');trigger.disabled=false;return;}trigger.disabled=false;
  if(!dependencies?.exists){toast(`${type==='teams'?'El':'La'} ${config.singular} ya no existe.`,'error');return;}if(!dependencies.can_delete){showEntityDependency(type,item,dependencies,trigger);return;}
  const confirmed=await confirmAction(`¿Seguro que deseas eliminar “${item.name}”? Esta acción no se puede deshacer.`,`Eliminar ${config.singular}`,{confirmLabel:`Eliminar ${config.singular}`,trigger});if(!confirmed)return;
  setButtonLoading(trigger,true,'Eliminando…');try{const result=await deleteCatalogEntitySafely(type,item.id);if(!result?.deleted){setButtonLoading(trigger,false);if(result?.reason==='children'||result?.reason==='products')showEntityDependency(type,item,result,trigger);else toast(`No pudimos eliminar ${article} ${config.singular}. Intenta nuevamente.`,'error');return;}
    if(type==='categories')categories=categories.filter(entity=>entity.id!==item.id);else if(type==='teams')teams=teams.filter(entity=>entity.id!==item.id);else brands=brands.filter(entity=>entity.id!==item.id);renderEntities(type);toast(`${config.title.slice(0,-1)} ${type==='teams'?'eliminado':'eliminada'} correctamente.`);removeCatalogEntityAsset(type,entityAssetUrl(type,item)).catch(error=>console.warn('No se pudo limpiar el activo administrado:',error));
  }catch(error){console.error(error);setButtonLoading(trigger,false);toast(`No pudimos eliminar ${article} ${config.singular}. Intenta nuevamente.`,'error');}
}

function renderEntities(type){
  const config=getEntityConfig(type);const state=getEntityState(type);const expandedParents=new Set();const registeredWord=type==='teams'?(config.items.length===1?'registrado':'registrados'):(config.items.length===1?'registrada':'registradas');$('#admin-content').innerHTML=heading('Organización',config.title,'Administra lo que los clientes usan para explorar.',`<button id="new-entity" class="btn btn--primary" type="button">+ ${config.button}</button>`)+`<section class="admin-panel entity-manager"><div class="admin-panel__head"><h2>${config.title}</h2><p>${config.items.length} ${config.items.length===1?config.singular:config.plural} ${registeredWord}</p></div>${entityToolbar(type,config,state)}<div id="entity-results" aria-live="polite"></div></section>`;
  const resultsRoot=$('#entity-results');const renderResults=()=>{const matching=config.items.filter(item=>entityMatches(type,item,state));let hierarchical=type==='categories'&&!state.search.trim()&&state.kind==='all'&&!state.parent;let visible;let pages;let meta;let rowOptions={};if(hierarchical){const roots=sortEntityItems(matching.filter(item=>!item.parent_id),state);if(!roots.length&&matching.length)hierarchical=false;else{const rootIds=new Set(roots.map(item=>item.id));const childCounts=new Map();const childrenByParent=new Map();matching.filter(item=>item.parent_id&&rootIds.has(item.parent_id)).forEach(item=>{if(!childrenByParent.has(item.parent_id))childrenByParent.set(item.parent_id,[]);childrenByParent.get(item.parent_id).push(item);});childrenByParent.forEach((children,parentId)=>{const ordered=sortEntityItems(children,state);childrenByParent.set(parentId,ordered);childCounts.set(parentId,ordered.length);});pages=Math.max(1,Math.ceil(roots.length/ENTITY_PAGE_SIZE));state.page=Math.min(state.page,pages);const pageRoots=roots.slice((state.page-1)*ENTITY_PAGE_SIZE,state.page*ENTITY_PAGE_SIZE);visible=pageRoots.flatMap(root=>[root,...(expandedParents.has(root.id)?childrenByParent.get(root.id)||[]:[])]);const childTotal=[...childCounts.values()].reduce((sum,count)=>sum+count,0);meta=`${roots.length} ${roots.length===1?'principal':'principales'} · ${childTotal} ${childTotal===1?'subcategoría':'subcategorías'}`;rowOptions={hierarchical:true,expandedParents,childCounts};}}
    if(!hierarchical){const filtered=orderEntityItems(type,matching,state);pages=Math.max(1,Math.ceil(filtered.length/ENTITY_PAGE_SIZE));state.page=Math.min(state.page,pages);visible=filtered.slice((state.page-1)*ENTITY_PAGE_SIZE,state.page*ENTITY_PAGE_SIZE);meta=`${filtered.length} ${filtered.length===1?'resultado':'resultados'}`;}
    resultsRoot.innerHTML=`<div class="results-meta entity-results-meta"><span>${meta}</span>${state.search||state.status!=='all'||state.kind!=='all'||state.parent||state.sort!=='az'?'<button data-clear-entities type="button">Limpiar</button>':''}</div>${visible.length?entityRows(type,visible,rowOptions):entityEmptyMarkup(config,state)}${paginationMarkup(state.page,pages)}`;bindPagination(resultsRoot,state,pages,renderResults);updateEntityControls(config,state);syncSectionUrl(type,state);};
  $('#new-entity').addEventListener('click',()=>openEntityForm(type));$('#entity-filters-button').addEventListener('click',event=>{const panel=$('#entity-filter-panel');panel.hidden=!panel.hidden;event.currentTarget.setAttribute('aria-expanded',String(!panel.hidden));});
  const search=debounce(value=>{state.search=value;state.page=1;renderResults();},200);$('#entity-search').addEventListener('input',event=>search(event.target.value));$$('[data-entity-quick]').forEach(button=>button.addEventListener('click',()=>{state[config.quickKey]=button.dataset.entityQuick;state.page=1;renderResults();}));$$('[data-entity-filter]').forEach(select=>select.addEventListener('change',event=>{state[event.target.dataset.entityFilter]=event.target.value;state.page=1;renderResults();}));
  resultsRoot.addEventListener('click',event=>{const clear=event.target.closest('[data-clear-entities]');if(clear){navigateTo(type);return;}const create=event.target.closest('[data-create-entity]');if(create){openEntityForm(type);return;}const row=event.target.closest('[data-entity-id]');if(!row)return;const item=config.items.find(entity=>entity.id===row.dataset.entityId);if(!item)return;const treeArea=event.target.closest('.data-row__thumb,.data-row__main');const toggle=event.target.closest('[data-toggle-category]')||(treeArea?row.querySelector('[data-toggle-category]'):null);if(toggle){if(expandedParents.has(item.id))expandedParents.delete(item.id);else expandedParents.add(item.id);renderResults();requestAnimationFrame(()=>resultsRoot.querySelector(`[data-toggle-category="${item.id}"]`)?.focus());return;}if(event.target.closest('[data-edit-entity]')){row.querySelector('.action-menu')?.removeAttribute('open');openEntityForm(type,item);}else if(event.target.closest('[data-delete-entity]')){row.querySelector('.action-menu')?.removeAttribute('open');requestEntityDeletion(type,item,event.target.closest('button'));}else if(event.target.closest('[data-view-related]'))navigateTo('products',relatedProductParams(type,item));});
  $('#entity-filter-panel').addEventListener('click',event=>{if(event.target.closest('[data-clear-entities]'))navigateTo(type);});renderResults();
}

function openEntityForm(type,item=null){
  const labels={categories:'categoría',teams:'equipo',brands:'marca'};
  const assetConfig={categories:{bucket:'category-images',folder:'categories',field:'image_url'},teams:{bucket:'team-crests',folder:'teams',field:'crest_url'},brands:{bucket:'brand-assets',folder:'brands',field:'logo_url'}}[type];
  const currentAsset=entityAssetUrl(type,item);const form=document.createElement('form');let previewUrl='';form.className='admin-form';
  const categoryAssetMarkup=type==='categories'?`<label class="entity-asset-field form-grid__full">Foto de la categoría <span>Opcional</span><input name="asset" type="file" accept="image/jpeg,image/png,image/webp,image/svg+xml"><small>PNG, JPG, WebP o SVG, máximo 5 MB. Si no cargas una foto, mostraremos las iniciales.</small></label><div class="entity-asset-preview form-grid__full" data-entity-asset-preview ${currentAsset?'':'hidden'}><img src="${currentAsset?escapeHtml(localAsset(currentAsset)):''}" alt="Vista previa de la categoría"><div><strong>Vista previa</strong><small>Se mostrará en las tarjetas de categorías.</small>${currentAsset?'<label class="check-field"><input name="remove_asset" type="checkbox"> Quitar foto actual</label>':''}</div></div>`:'';
  form.innerHTML=`<div class="form-grid"><label>Nombre<input name="name" value="${escapeHtml(item?.name||'')}" required></label><label>Slug<input name="slug" value="${escapeHtml(item?.slug||'')}" placeholder="Automático"></label>${type==='categories'?`<label>Categoría superior<select name="parent_id"><option value="">Ninguna</option>${categories.filter(c=>c.id!==item?.id&&!c.parent_id).map(c=>`<option value="${c.id}" ${item?.parent_id===c.id?'selected':''}>${escapeHtml(c.name)}</option>`).join('')}</select></label><label class="form-grid__full">Descripción<textarea name="description">${escapeHtml(item?.description||'')}</textarea></label>${categoryAssetMarkup}`:''}${type==='teams'?`<label>Tipo<select name="type"><option value="club" ${item?.type==='club'?'selected':''}>Club</option><option value="national_team" ${item?.type==='national_team'?'selected':''}>Selección</option><option value="colombian_team" ${item?.type==='colombian_team'?'selected':''}>Equipo colombiano</option></select></label><label>Escudo<input name="asset" type="file" accept="image/*"></label>`:''}${type==='brands'?'<label>Logo opcional<input name="asset" type="file" accept="image/*"></label>':''}<label class="check-field"><input name="active" type="checkbox" ${item?.active!==false?'checked':''}> Visible y activo</label></div><div class="form-actions"><button class="btn btn--primary" type="submit">Guardar</button></div>`;
  const modal=openModal({title:`${item?'Editar':'Nueva'} ${labels[type]}`,content:form,onClose:()=>{if(previewUrl)URL.revokeObjectURL(previewUrl);}});
  if(type==='categories')form.elements.asset.addEventListener('change',()=>{const file=form.elements.asset.files[0];if(!file)return;if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=URL.createObjectURL(file);const preview=form.querySelector('[data-entity-asset-preview]');preview.hidden=false;preview.querySelector('img').src=previewUrl;form.elements.remove_asset&&(form.elements.remove_asset.checked=false);});
  form.addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;const data=new FormData(form);const file=form.elements.asset?.files?.[0];let uploadedUrl='';if(file&&file.size>5242880){toast('La imagen debe pesar máximo 5 MB.','error');return;}setButtonLoading(button,true,'Guardando…');try{const values={name:data.get('name').trim(),slug:data.get('slug').trim()||slugify(data.get('name')),active:data.has('active')};if(type==='categories')Object.assign(values,{parent_id:data.get('parent_id')||null,description:data.get('description').trim()||null});if(type==='teams')values.type=data.get('type');if(file){uploadedUrl=await uploadImage(assetConfig.bucket,file,assetConfig.folder);values[assetConfig.field]=uploadedUrl;}else if(type==='categories'&&data.has('remove_asset'))values.image_url=null;await saveRow(type,values,item?.id);await refreshData();modal.close();renderEntities(type);toast('Cambios guardados');if(currentAsset&&(uploadedUrl||(type==='categories'&&data.has('remove_asset'))))removeCatalogEntityAsset(type,currentAsset).catch(error=>console.warn('No se pudo limpiar la imagen anterior:',error));}catch(error){console.error(error);if(uploadedUrl)removeCatalogEntityAsset(type,uploadedUrl).catch(()=>{});toast('No pudimos guardar. Revisa que el nombre y slug no estén repetidos.','error');setButtonLoading(button,false);}});
}

function renderPromotions(){
  const promoProducts=products.filter(p=>p.promo_price!=null);$('#admin-content').innerHTML=heading('Precios especiales','Promociones','Configura precio y vigencia directamente sobre cada producto.')+`<section class="admin-panel"><div class="data-list">${products.map(p=>`<article class="data-row" data-promo="${p.id}"><div class="data-row__main"><strong>${escapeHtml(p.name)}</strong><small>${p.promo_price?`${formatMoney(p.promo_price)} · ${isPromoActive(p)?'Activa':'Fuera de vigencia'}`:'Sin promoción'}</small></div><span class="status-pill ${isPromoActive(p)?'status-pill--active':''}">${isPromoActive(p)?'Activa':'Inactiva'}</span><div class="data-row__actions"><button class="small-btn" data-edit-promo type="button">Configurar</button></div></article>`).join('')}</div></section>`;
  $$('[data-promo]').forEach(row=>row.querySelector('button').addEventListener('click',()=>openPromoForm(products.find(p=>p.id===row.dataset.promo))));
}
function openPromoForm(product){const form=document.createElement('form');form.className='admin-form';form.innerHTML=`<p><strong>${escapeHtml(product.name)}</strong><br>Precio normal: ${formatMoney(product.base_price)}</p><div class="form-grid"><label>Precio promocional<input name="promo_price" type="number" min="0" max="${product.base_price-1}" value="${product.promo_price||''}"></label><label>Inicio<input name="promo_start" type="datetime-local" value="${toLocalInput(product.promo_start)}"></label><label>Finalización<input name="promo_end" type="datetime-local" value="${toLocalInput(product.promo_end)}"></label></div><div class="form-actions"><button class="btn btn--primary" type="submit">Guardar promoción</button><button class="btn btn--danger" data-remove-promo type="button">Quitar promoción</button></div>`;const modal=openModal({title:'Configurar promoción',content:form});const save=async values=>{try{await saveRow('products',values,product.id);await refreshData();modal.close();renderPromotions();toast('Promoción actualizada');}catch(error){console.error(error);toast('No pudimos guardar la promoción.','error');}};form.addEventListener('submit',event=>{event.preventDefault();const data=new FormData(form);save({promo_price:data.get('promo_price')?Number(data.get('promo_price')):null,promo_start:data.get('promo_start')?new Date(data.get('promo_start')).toISOString():null,promo_end:data.get('promo_end')?new Date(data.get('promo_end')).toISOString():null});});form.querySelector('[data-remove-promo]').addEventListener('click',()=>save({promo_price:null,promo_start:null,promo_end:null}));}

async function renderSettings(){
  const[settings,payments]=await Promise.all([getSettings(),getPaymentMethods({all:true})]);$('#admin-content').innerHTML=heading('Tu negocio','Configuración','Estos datos aparecen en la tienda y el checkout.')+`<form id="settings-form" class="admin-form"><section class="admin-form__section"><h3>Información del negocio</h3><div class="form-grid"><label>Nombre comercial<input name="business_name" value="${escapeHtml(settings.business_name||'')}" required></label><label>WhatsApp con indicativo<input name="whatsapp" value="${escapeHtml(settings.whatsapp||'')}" required inputmode="tel"></label><label>Teléfono<input name="phone" value="${escapeHtml(settings.phone||'')}"></label><label>Correo<input name="email" type="email" value="${escapeHtml(settings.email||'')}"></label><label>Dirección<input name="address" value="${escapeHtml(settings.address||'')}"></label><label>Ciudad<input name="city" value="${escapeHtml(settings.city||'')}"></label><label>Horario<input name="schedule" value="${escapeHtml(settings.schedule||'')}"></label><label>Instagram<input name="instagram" value="${escapeHtml(settings.instagram||'')}"></label><label>Facebook<input name="facebook" value="${escapeHtml(settings.facebook||'')}"></label><label>TikTok<input name="tiktok" value="${escapeHtml(settings.tiktok||'')}"></label><label class="form-grid__full">URL Google Maps<input name="maps_url" type="url" value="${escapeHtml(settings.maps_url||'')}"></label><label>Después de abrir WhatsApp<select name="checkout_behavior"><option value="keep" ${settings.checkout_behavior==='keep'?'selected':''}>Mantener carrito</option><option value="clear" ${settings.checkout_behavior==='clear'?'selected':''}>Vaciar carrito</option></select></label><label>Logo oficial<input id="site-logo" type="file" accept="image/*"></label></div></section><div class="form-actions"><button class="btn btn--primary" type="submit">Guardar configuración</button></div></form><section class="admin-panel"><div class="admin-panel__head"><h2>Métodos de pago</h2><button id="new-payment" class="btn btn--ghost" type="button">+ Agregar</button></div><div id="payment-list">${paymentRows(payments)}</div></section>`;
  $('#settings-form').addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;setButtonLoading(button,true,'Guardando…');const data=new FormData(event.currentTarget);const fields=['business_name','whatsapp','phone','email','address','city','schedule','instagram','facebook','tiktok','maps_url','checkout_behavior'];const values={};fields.forEach(field=>values[field]=data.get(field)||null);try{const file=$('#site-logo').files[0];if(file)values.logo_url=await uploadImage('site-assets',file,'logo');await saveSettings(values);toast('Configuración guardada');setButtonLoading(button,false);}catch(error){console.error(error);toast('No pudimos guardar la configuración.','error');setButtonLoading(button,false);}});
  $('#new-payment').addEventListener('click',()=>openPaymentForm(null,payments));bindPayments(payments);
}
function paymentMethodThumb(item){return `<div class="data-row__thumb entity-thumb payment-method-thumb">${item.logo_url?`<img src="${escapeHtml(localAsset(item.logo_url))}" alt="" loading="lazy" width="52" height="52">`:`<span aria-hidden="true">${escapeHtml(paymentInitials(item.name))}</span>`}</div>`;}
function paymentRows(items){return `<div class="data-list">${items.map(item=>`<article class="data-row payment-method-row" data-payment="${item.id}">${paymentMethodThumb(item)}<div class="data-row__main"><strong>${escapeHtml(item.name)}</strong><small>${escapeHtml(item.instructions||'')}</small></div><span class="status-pill status-pill--${item.active?'active':'hidden'}">${item.active?'Activo':'Oculto'}</span><div class="data-row__actions"><button class="small-btn" data-edit type="button">Editar</button><button class="small-btn small-btn--danger" data-delete type="button">Eliminar</button></div></article>`).join('')}</div>`;}
function bindPayments(items){$$('[data-payment]').forEach(row=>{const item=items.find(x=>x.id===row.dataset.payment);const editButton=row.querySelector('[data-edit]');const deleteButton=row.querySelector('[data-delete]');editButton.addEventListener('click',()=>openPaymentForm(item,items));deleteButton.addEventListener('click',async()=>{const confirmed=await confirmAction(`¿Eliminar ${item.name}? Esta acción no se puede deshacer.`,'Eliminar método de pago',{confirmLabel:'Eliminar método',trigger:deleteButton});if(!confirmed)return;setButtonLoading(deleteButton,true,'Eliminando…');try{await deleteRow('payment_methods',item.id);await renderSettings();toast('Método eliminado');if(item.logo_url)removePaymentMethodAsset(item.logo_url).catch(error=>console.warn('No se pudo limpiar el logo del método:',error));}catch(error){console.error(error);setButtonLoading(deleteButton,false);toast('No pudimos eliminar el método. Intenta nuevamente.','error');}});});}
function openPaymentForm(item,items){
  const form=document.createElement('form');let previewUrl='';
  form.className='admin-form';
  form.innerHTML=`<div class="form-grid"><label>Nombre<input name="name" value="${escapeHtml(item?.name||'')}" required></label><label>Orden<input name="sort_order" type="number" min="0" value="${item?.sort_order??items.length+1}"></label><label class="form-grid__full">Instrucciones<textarea name="instructions">${escapeHtml(item?.instructions||'')}</textarea></label><label class="payment-logo-field form-grid__full">Logo de la entidad <span>Opcional</span><input name="logo" type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml"><small>PNG, JPG, WebP o SVG. Si no cargas uno, mostraremos las iniciales.</small></label><div class="payment-logo-preview form-grid__full" data-payment-logo-preview ${item?.logo_url?'':'hidden'}><img src="${item?.logo_url?escapeHtml(localAsset(item.logo_url)):''}" alt="Vista previa del logo"><div><strong>Vista previa</strong><small>Se mostrará en el checkout.</small>${item?.logo_url?'<label class="check-field"><input name="remove_logo" type="checkbox"> Quitar logo actual</label>':''}</div></div><label class="check-field"><input name="active" type="checkbox" ${item?.active!==false?'checked':''}> Activo</label></div><div class="form-actions"><button class="btn btn--primary" type="submit">Guardar</button></div>`;
  const modal=openModal({title:item?'Editar método':'Nuevo método de pago',content:form,onClose:()=>{if(previewUrl)URL.revokeObjectURL(previewUrl);}});
  form.elements.logo.addEventListener('change',()=>{const file=form.elements.logo.files[0];if(!file)return;if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=URL.createObjectURL(file);const preview=form.querySelector('[data-payment-logo-preview]');preview.hidden=false;preview.querySelector('img').src=previewUrl;form.elements.remove_logo&&(form.elements.remove_logo.checked=false);});
  form.addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;const data=new FormData(form);const file=form.elements.logo.files[0];let uploadedUrl='';if(file&&file.size>5242880){toast('El logo debe pesar máximo 5 MB.','error');return;}setButtonLoading(button,true,'Guardando…');try{const values={name:data.get('name').trim(),instructions:data.get('instructions').trim()||null,sort_order:Number(data.get('sort_order')||0),active:data.has('active')};if(file){uploadedUrl=await uploadImage('site-assets',file,'payment-methods');values.logo_url=uploadedUrl;}else if(data.has('remove_logo'))values.logo_url=null;await saveRow('payment_methods',values,item?.id);modal.close();await renderSettings();toast('Método guardado');if(item?.logo_url&&(uploadedUrl||data.has('remove_logo')))removePaymentMethodAsset(item.logo_url).catch(error=>console.warn('No se pudo limpiar el logo anterior:',error));}catch(error){console.error(error);if(uploadedUrl)removePaymentMethodAsset(uploadedUrl).catch(()=>{});toast('No pudimos guardar el método.','error');setButtonLoading(button,false);}});
}
