import { getHomepageBanners, removeBannerImage, saveHomepageBanners, uploadBannerImage } from '../lib/api.js';
import { createHomeBanner, safeBannerLink, validBannerInterval, BANNER_LIMIT } from '../lib/home-banner.js';
import { prepareProductImage, inspectImageFile, imageProcessingMessage, formatBytes } from '../lib/image-processor.js';
import { escapeHtml } from '../lib/helpers.js';
import { confirmAction } from './modal.js';
import { toast } from './toast.js';

const icon=(name)=>({
  campaign:'<svg aria-hidden="true" focusable="false" viewBox="0 0 24 24"><path d="M4 13V8a2 2 0 0 1 2-2h3l8-3v15l-8-3H6a2 2 0 0 1-2-2Z"/><path d="m9 15 1 5H7l-1-5M20 8v5"/></svg>',
  image:'<svg aria-hidden="true" focusable="false" viewBox="0 0 24 24"><rect x="3" y="4" width="18" height="16" rx="2"/><circle cx="8.5" cy="9" r="1.5"/><path d="m4 17 5-5 4 4 2-2 5 4"/></svg>',
  monitor:'<svg aria-hidden="true" focusable="false" viewBox="0 0 24 24"><rect x="2" y="4" width="20" height="14" rx="2"/><path d="M8 22h8M12 18v4"/></svg>',
  phone:'<svg aria-hidden="true" focusable="false" viewBox="0 0 24 24"><rect x="6" y="2" width="12" height="20" rx="2"/><path d="M10 5h4M11 19h2"/></svg>',
  upload:'<svg aria-hidden="true" focusable="false" viewBox="0 0 24 24"><path d="M12 16V4m0 0L7 9m5-5 5 5M4 15v4a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-4"/></svg>',
  trash:'<svg aria-hidden="true" focusable="false" viewBox="0 0 24 24"><path d="M4 7h16M9 7V4h6v3M7 7l1 14h8l1-14M10 11v6M14 11v6"/></svg>',
  warning:'<svg aria-hidden="true" focusable="false" viewBox="0 0 24 24"><path d="M12 3 2 21h20L12 3Z"/><path d="M12 9v5m0 3h.01"/></svg>',
  check:'<svg aria-hidden="true" focusable="false" viewBox="0 0 24 24"><path d="m5 12 4 4L19 6"/></svg>',
  chevron:'<svg aria-hidden="true" focusable="false" viewBox="0 0 24 24"><path d="m7 10 5 5 5-5"/></svg>'
}[name]||'');
const limits=v=>({targetBytes:(v==='mobile'?450:700)*1024,maxOutputBytes:1048576,maxLongEdge:v==='mobile'?1080:1920,minLongEdge:v==='mobile'?900:1500,maxPixels:220_000_000});
const hydrate=(r,i=0)=>({...r,key:r.id||crypto.randomUUID(),files:{},objectUrls:{},media:{},errors:{},status:'',warning:'',processingVariant:'',expanded:i===0,isNew:!r.id});

export function mountBannerEditor(root,settings,initialRows,{unavailable=false}={}){
  let rows=initialRows.map(hydrate),enabled=Boolean(settings.banner_enabled),interval=String(settings.banner_interval_seconds??5);
  let previewMode=matchMedia('(max-width:600px)').matches?'mobile':'desktop',previewController={stop(){}},saving=false,dirty=false,disposed=false;
  const removed=[],removedAssets=[];
  root.innerHTML=`<section class="banner-studio" aria-labelledby="banner-title">
    <header class="banner-studio__hero"><div class="banner-studio__identity"><span class="banner-studio__hero-icon">${icon('campaign')}</span><div><span class="banner-studio__eyebrow">Contenido de inicio</span><h2 id="banner-title">Banner publicitario</h2><p>Administra las promociones visuales que aparecen en la página de inicio.</p></div></div>
      <label class="banner-switch"><span><strong id="banner-visibility">${enabled?'Visible en la tienda':'Oculto en la tienda'}</strong><small>Controla la visibilidad del carrusel</small></span><input id="banner-enabled" type="checkbox" ${enabled?'checked':''}><i aria-hidden="true"><b></b></i></label></header>
    <div id="banner-disabled-note" class="banner-studio__notice" ${enabled?'hidden':''}>${icon('warning')}<span>Puedes seguir editando los banners, pero no aparecerán en la tienda hasta activar esta opción.</span></div>
    <div class="banner-studio__layout"><div class="banner-studio__editor">
      <section class="banner-panel"><div class="banner-panel__heading"><span>01</span><div><h3>Configuración del carrusel</h3><p>Ajusta la rotación y administra tus espacios disponibles.</p></div></div>
        <div class="banner-quick"><label>Tiempo entre banners<div class="banner-interval"><input id="banner-interval" type="number" min=".5" max="60" step=".1" value="${escapeHtml(interval)}"><b>segundos</b></div><small>Tiempo que cada imagen permanece visible.</small></label>
          <div class="banner-usage"><strong id="banner-count"></strong><small id="banner-limit-copy"></small><div id="banner-progress"></div></div>
          <button id="banner-add" type="button" class="btn banner-add"><b>+</b> Agregar banner</button></div>
        <p id="banner-fast-warning" class="banner-alert" hidden>${icon('warning')}<span>Una rotación muy rápida puede dificultar la lectura.</span></p></section>
      <section class="banner-panel banner-guide"><div class="banner-panel__heading"><span>02</span><div><h3>Prepara tus imágenes</h3><p>Usa estas medidas para obtener un resultado nítido.</p></div></div>
        <div class="banner-guide__grid"><article><i>${icon('monitor')}</i><div><strong>Escritorio <em>Obligatoria</em></strong><b>1920 × 640 px</b><small>Proporción 3:1 · hasta 700 KB<br>JPG, PNG, WebP o AVIF</small></div></article><article><i>${icon('phone')}</i><div><strong>Móvil <em>Opcional</em></strong><b>1080 × 600 px</b><small>Proporción 1.8:1 · hasta 450 KB<br>Usaremos la imagen de escritorio si la omites.</small></div></article></div>
        <p class="banner-guide__tip">${icon('warning')}<span>Evita textos importantes cerca de los bordes; la imagen puede recortarse ligeramente según el dispositivo.</span></p></section>
      <section class="banner-panel"><div class="banner-panel__heading"><span>03</span><div><h3>Diapositivas</h3><p>Ordena, completa y activa tus promociones.</p></div></div><div id="banner-list" class="banner-list"></div></section>
    </div><aside class="banner-preview-card"><div class="banner-preview-card__head"><span><i></i> En vivo</span><h3>Vista previa en la tienda</h3><p>Así verán tus clientes el carrusel.</p><div class="banner-device-tabs" role="group" aria-label="Tamaño de vista previa"><button type="button" data-preview="mobile">${icon('phone')} Móvil</button><button type="button" data-preview="desktop">${icon('monitor')} Escritorio</button></div></div>
      <div id="banner-preview-frame" class="banner-device-frame"><div class="banner-device-frame__chrome"><i></i><i></i><i></i></div><div id="banner-preview" class="banner-editor__preview"></div></div><p id="banner-preview-state"></p></aside></div>
    <p id="banner-error" class="banner-save-error" role="alert" tabindex="-1" hidden></p>
    <footer class="banner-savebar"><div><span></span><p><strong id="banner-save-state">Sin cambios</strong><small id="banner-save-help">La configuración está actualizada.</small></p></div><button id="banner-save" type="button" class="btn btn--primary" disabled>Guardar cambios del banner</button></footer>
  </section>`;
  const $=s=>root.querySelector(s),list=$('#banner-list'),preview=$('#banner-preview'),frame=$('#banner-preview-frame'),enabledInput=$('#banner-enabled'),intervalInput=$('#banner-interval'),add=$('#banner-add'),save=$('#banner-save'),error=$('#banner-error');
  const urlFor=(r,v)=>r.objectUrls[v]||r[`${v}_image_url`]||'';
  const releaseVariant=(r,v)=>{if(r.objectUrls[v])URL.revokeObjectURL(r.objectUrls[v]);delete r.objectUrls[v];};
  const release=r=>{Object.values(r.objectUrls).forEach(url=>URL.revokeObjectURL(url));r.objectUrls={};};
  const report=m=>{error.textContent=m;error.hidden=!m;if(m)error.focus({preventScroll:true});};
  const saveState=(a,b)=>{$('#banner-save-state').textContent=a;$('#banner-save-help').textContent=b;$('.banner-savebar').dataset.state=a;};
  const markDirty=()=>{if(saving||unavailable)return;dirty=true;save.disabled=false;saveState('Cambios sin guardar','Guarda para publicar esta configuración.');};
  function renderPreview(){
    previewController.stop();frame.dataset.device=previewMode;
    root.querySelectorAll('[data-preview]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.preview===previewMode)));
    const state=$('#banner-preview-state'),active=rows.filter(r=>r.active&&urlFor(r,'desktop'));
    if(!enabled||!active.length){preview.className='banner-editor__preview is-empty';preview.innerHTML=`<i>${icon('image')}</i><strong>${enabled?'Tu vista previa aparecerá aquí':'Oculto en la tienda'}</strong><small>${enabled?'Agrega una imagen de escritorio y activa el banner.':'Activa el carrusel para mostrarlo.'}</small>`;state.textContent=enabled?'No hay diapositivas activas.':'El banner no será visible en la tienda.';return;}
    const items=rows.map(r=>({...r,desktop_image_url:previewMode==='mobile'?(urlFor(r,'mobile')||urlFor(r,'desktop')):urlFor(r,'desktop'),mobile_image_url:previewMode==='mobile'?'':urlFor(r,'mobile')}));
    preview.className='banner-editor__preview';preview.replaceChildren();previewController=createHomeBanner(preview,{enabled,intervalSeconds:Number(interval),banners:items},{preview:true});state.textContent=`${active.length} ${active.length===1?'diapositiva activa':'diapositivas activas'} · cada ${interval||'—'} s`;
  }
  function zone(r,v){
    const mobile=v==='mobile',url=urlFor(r,v),id=`banner-${r.key}-${v}`,title=`Imagen para ${mobile?'móvil':'escritorio'}`,err=r.errors[v]||'';
    if(url){const m=r.media[v],meta=m?`${m.width} × ${m.height} px · ${formatBytes(m.bytes)} · ${m.format}`:'Imagen guardada';return `<div class="banner-media ${mobile?'is-mobile':''}"><div class="banner-media__image"><img src="${escapeHtml(url)}" alt="Vista previa ${mobile?'móvil':'de escritorio'}"><span>${mobile?'Móvil':'Escritorio'}</span></div><div class="banner-media__foot"><p><strong>${title}</strong><small>${meta}</small></p><label for="${id}">Reemplazar</label><button type="button" data-action="remove-image" data-variant="${v}">${icon('trash')}<span>Eliminar</span></button></div><input id="${id}" class="banner-file-input" data-file="${v}" type="file" accept="image/jpeg,image/png,image/webp,image/avif">${err?`<p class="banner-upload-error">${err}</p>`:''}</div>`;}
    return `<div class="banner-dropzone ${err?'has-error':''} ${r.processingVariant===v?'is-processing':''}" data-dropzone="${v}"><input id="${id}" class="banner-file-input" data-file="${v}" type="file" accept="image/jpeg,image/png,image/webp,image/avif"><i>${mobile?icon('phone'):icon('upload')}</i><strong>${title} <em>${mobile?'Opcional':'Obligatoria'}</em></strong><small>${mobile?'1080 × 600 px · 1.8:1':'1920 × 640 px · 3:1'}</small><label for="${id}">Seleccionar imagen</label><span>o arrastra el archivo aquí</span><b>JPG, PNG, WebP o AVIF</b>${err?`<p class="banner-upload-error">${err}</p>`:''}</div>`;
  }
  function card(r,i){
    const image=urlFor(r,'desktop'),complete=Boolean(image&&r.alt_text?.trim()),link=String(r.link_url||''),valid=!link.trim()||safeBannerLink(link);
    return `<article class="banner-slide-card ${r.expanded?'is-open':''}" data-key="${escapeHtml(r.key)}"><header><button type="button" class="banner-slide-card__toggle" data-action="toggle" aria-expanded="${r.expanded}" aria-controls="banner-body-${escapeHtml(r.key)}">${image?`<img src="${escapeHtml(image)}" alt="">`:`<i>${icon('image')}</i>`}<span><b>Banner ${i+1}</b>${r.isNew?'<em>Nuevo</em>':''}<small>${complete?'Listo para publicar':'Completa la información'}</small></span><span class="banner-badges"><em class="${r.active?'on':''}">${r.active?'Activo':'Inactivo'}</em><em class="${complete?'done':'missing'}">${complete?'Completo':image?'Incompleto':'Falta imagen'}</em></span>${icon('chevron')}</button><div class="banner-slide-card__tools"><button data-action="up" ${i===0?'disabled':''} aria-label="Mover arriba">↑</button><button data-action="down" ${i===rows.length-1?'disabled':''} aria-label="Mover abajo">↓</button><button data-action="remove" class="danger" aria-label="Eliminar banner">${icon('trash')}</button></div></header>
      <div id="banner-body-${escapeHtml(r.key)}" class="banner-slide-card__body" ${r.expanded?'':'hidden'}><div class="banner-item-status"><label><input data-field="active" type="checkbox" ${r.active?'checked':''}><i><b></b></i><strong>${r.active?'Banner activo':'Banner inactivo'}</strong></label><small>${r.active?'Se incluirá en la rotación.':'Se conservará sin mostrarse en la tienda.'}</small></div>
      <section><h4>Imágenes del banner</h4><p>La versión móvil adapta mejor el contenido a pantallas estrechas.</p><div class="banner-upload-grid">${zone(r,'desktop')}${zone(r,'mobile')}</div></section>
      <section><h4>Información del banner</h4><p>Ayuda a entender la promoción y llegar al destino correcto.</p><div class="banner-info-grid"><label>Descripción de la imagen <em>Obligatoria</em><input data-field="alt_text" maxlength="200" value="${escapeHtml(r.alt_text||'')}" placeholder="Promoción de uniformes deportivos"><small>Describe brevemente lo que aparece. <b data-alt-count>${String(r.alt_text||'').length}/200</b></small></label><label>Enlace al hacer clic <em>Opcional</em><div class="banner-link ${link.trim()?(valid?'valid':'invalid'):''}"><input data-field="link_url" value="${escapeHtml(link)}" placeholder="promociones.html o https://..."><i>${valid&&link.trim()?icon('check'):''}</i></div><small>${valid?'El cliente será dirigido aquí cuando pulse el banner.':'Usa una dirección interna o un enlace https://.'}</small></label></div></section>
      <div aria-live="polite">${r.status?`<p class="banner-process">${escapeHtml(r.status)}</p>`:''}${r.warning?`<p class="banner-alert">${icon('warning')}<span>${escapeHtml(r.warning)}</span></p>`:''}</div></div></article>`;
  }
  function render(focus=''){
    list.innerHTML=rows.length?rows.map(card).join(''):`<div class="banner-empty"><i>${icon('campaign')}</i><h4>Crea tu primer banner</h4><p>Destaca promociones, productos o campañas en la página de inicio.</p><small>Escritorio 1920 × 640 px · Móvil 1080 × 600 px</small><button data-empty-add class="btn btn--primary">Agregar primer banner</button></div>`;
    $('#banner-count').textContent=`${rows.length} de ${BANNER_LIMIT} banners utilizados`;$('#banner-limit-copy').textContent=rows.length===BANNER_LIMIT?'Límite de 5 banners alcanzado':`${BANNER_LIMIT-rows.length} espacios disponibles`;$('#banner-progress').innerHTML=Array.from({length:5},(_,i)=>`<i class="${i<rows.length?'used':''}"></i>`).join('');add.disabled=unavailable||rows.length>=5||saving;$('#banner-fast-warning').hidden=!(Number(interval)>=.5&&Number(interval)<2.5);renderPreview();
    if(focus)requestAnimationFrame(()=>{const el=list.querySelector(`[data-key="${CSS.escape(focus)}"]`);el?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth',block:'nearest'});el?.querySelector('.banner-dropzone label')?.focus({preventScroll:true});});
  }
  function addRow(){if(add.disabled)return;rows.forEach(r=>r.expanded=false);const r=hydrate({id:null,desktop_image_url:'',mobile_image_url:'',alt_text:'',link_url:'',active:true},rows.length);r.expanded=true;rows.push(r);markDirty();render(r.key);}
  async function process(r,v,file){
    if(!file)return;r.errors[v]='';r.processingVariant=v;r.status='Preparando imagen…';render();
    try{const info=await inspectImageFile(file);if(!['image/jpeg','image/png','image/webp','image/avif'].includes(info.mime))throw new Error('Usa JPG, PNG, WebP o AVIF.');
      const p=await prepareProductImage(file,{limits:limits(v),forceOptimize:true,onStatus:s=>{r.status=s==='optimizing'?'Optimizando imagen…':'Procesando imagen…';list.querySelector(`[data-key="${r.key}"] .banner-process`)?.replaceChildren(r.status);}});if(p.file.size>1048576)throw new Error('La imagen optimizada supera 1 MB.');
      releaseVariant(r,v);r.files[v]=p.file;r.objectUrls[v]=URL.createObjectURL(p.file);r.media[v]={width:p.finalWidth,height:p.finalHeight,bytes:p.finalBytes,format:p.mime.replace('image/','').toUpperCase()};const ratio=p.finalWidth/p.finalHeight,expected=v==='mobile'?1.8:3;r.warning=(p.finalWidth<(v==='mobile'?900:1500)||Math.abs(ratio-expected)>.35)?'La imagen puede recortarse por su resolución o proporción.':'Proporción recomendada. Imagen lista para guardar.';r.status='Imagen preparada correctamente.';markDirty();
    }catch(e){r.errors[v]=e.code?imageProcessingMessage(e):e.message;r.status='';}finally{r.processingVariant='';}render();
  }
  enabledInput.addEventListener('change',()=>{enabled=enabledInput.checked;$('#banner-visibility').textContent=enabled?'Visible en la tienda':'Oculto en la tienda';$('#banner-disabled-note').hidden=enabled;$('.banner-studio__layout').classList.toggle('muted',!enabled);markDirty();renderPreview();});
  intervalInput.addEventListener('input',()=>{interval=intervalInput.value;markDirty();render();});root.querySelectorAll('[data-preview]').forEach(b=>b.addEventListener('click',()=>{previewMode=b.dataset.preview;renderPreview();}));add.addEventListener('click',addRow);
  list.addEventListener('click',async e=>{if(e.target.closest('[data-empty-add]'))return addRow();const b=e.target.closest('[data-action]');if(!b||saving)return;const pos=rows.findIndex(r=>r.key===b.closest('[data-key]')?.dataset.key);if(pos<0)return;const r=rows[pos],a=b.dataset.action;if(a==='toggle'){r.expanded=!r.expanded;return render();}if(a==='up'||a==='down'){const n=pos+(a==='up'?-1:1);if(n<0||n>=rows.length)return;[rows[pos],rows[n]]=[rows[n],rows[pos]];markDirty();}else if(a==='remove'){if(r.id&&!await confirmAction('¿Eliminar este banner? El cambio se aplicará al guardar.','Eliminar banner',{confirmLabel:'Eliminar banner',trigger:b}))return;removed.push(r);rows.splice(pos,1);markDirty();}else if(a==='remove-image'){const v=b.dataset.variant;if(r[`${v}_image_url`])removedAssets.push(r[`${v}_image_url`]);r[`${v}_image_url`]='';delete r.files[v];delete r.media[v];r.warning='';releaseVariant(r,v);markDirty();}render();});
  list.addEventListener('input',e=>{const input=e.target.closest('[data-field]');if(!input)return;const r=rows.find(x=>x.key===input.closest('[data-key]').dataset.key);r[input.dataset.field]=input.type==='checkbox'?input.checked:input.value;if(input.dataset.field==='alt_text')input.closest('label').querySelector('[data-alt-count]').textContent=`${input.value.length}/200`;if(input.dataset.field==='link_url'){const box=input.closest('.banner-link'),has=input.value.trim(),valid=!has||safeBannerLink(input.value);box.classList.toggle('valid',Boolean(has&&valid));box.classList.toggle('invalid',Boolean(has&&!valid));box.querySelector('i').innerHTML=has&&valid?icon('check'):'';box.parentElement.querySelector('small').textContent=valid?'El cliente será dirigido aquí cuando pulse el banner.':'Usa una dirección interna o un enlace https://.';}markDirty();if(input.dataset.field==='active')render();else renderPreview();});
  list.addEventListener('change',e=>{const input=e.target.closest('[data-file]');if(input?.files?.[0])process(rows.find(r=>r.key===input.closest('[data-key]').dataset.key),input.dataset.file,input.files[0]);});
  ['dragenter','dragover','dragleave','drop'].forEach(type=>list.addEventListener(type,e=>{const z=e.target.closest('[data-dropzone]');if(!z)return;e.preventDefault();z.classList.toggle('dragging',type==='dragenter'||type==='dragover');if(type==='drop'&&e.dataTransfer?.files[0])process(rows.find(r=>r.key===z.closest('[data-key]').dataset.key),z.dataset.dropzone,e.dataTransfer.files[0]);}));
  save.addEventListener('click',async()=>{if(saving||unavailable||!dirty)return;report('');if(!validBannerInterval(interval))return report('El tiempo debe estar entre 0.5 y 60 segundos.');for(const[i,r]of rows.entries()){if(!urlFor(r,'desktop'))return report(`El banner ${i+1} necesita imagen de escritorio.`);if(!r.alt_text?.trim())return report(`Escribe la descripción del banner ${i+1}.`);if(r.link_url?.trim()&&!safeBannerLink(r.link_url))return report(`El enlace del banner ${i+1} no es válido.`);}
    saving=true;save.disabled=true;add.disabled=true;save.innerHTML='<span class="spinner"></span> Guardando…';saveState('Guardando…','Estamos publicando tus cambios.');const uploaded=[];let committed=false;
    try{const payload=[];for(const[i,r]of rows.entries()){let desktop=r.desktop_image_url,mobile=r.mobile_image_url;for(const v of['desktop','mobile'])if(r.files[v]){r.status=`Subiendo imagen ${v==='desktop'?'de escritorio':'móvil'}…`;const u=await uploadBannerImage(r.files[v]);uploaded.push(u);if(v==='desktop')desktop=u;else mobile=u;}payload.push({id:r.id||null,desktop_image_url:desktop,mobile_image_url:mobile||null,alt_text:r.alt_text.trim(),link_url:safeBannerLink(r.link_url)||null,active:r.active,sort_order:i+1});}await saveHomepageBanners(enabled,Number(interval),payload);committed=true;const persisted=await getHomepageBanners({ all: true });const stale=[...removedAssets,...[...removed,...rows].flatMap(r=>[r.desktop_image_url,r.mobile_image_url])].filter(u=>u&&!persisted.some(x=>x.desktop_image_url===u||x.mobile_image_url===u));await Promise.allSettled(stale.map(removeBannerImage));rows.forEach(release);removed.forEach(release);removed.length=0;removedAssets.length=0;rows=persisted.map(hydrate);dirty=false;toast('Banners guardados correctamente');saveState('Guardado','La configuración se guardó correctamente.');
    }catch(e){console.error('No se pudieron guardar los banners',e);if(!committed)await Promise.allSettled(uploaded.map(removeBannerImage));report('No pudimos guardar los banners. Tus cambios siguen aquí.');saveState('Cambios sin guardar','Corrige el error y vuelve a intentarlo.');}finally{saving=false;save.disabled=!dirty;save.textContent='Guardar cambios del banner';render();}});
  $('.banner-studio__layout').classList.toggle('muted',!enabled);render();if(unavailable){report('La migración de banners no está disponible.');add.disabled=true;save.disabled=true;}return()=>{disposed=true;previewController.stop();[...rows,...removed].forEach(release);};
}
